import type { DailyChallenge } from "@bao/shared";
import { getGamificationChallengeIcon } from "@bao/shared";

const resolveChallengeIcon = (challengeId: string): string =>
  getGamificationChallengeIcon(challengeId);

export const DAILY_CHALLENGE_DEFINITIONS: DailyChallenge[] = [
  {
    id: "update_profile",
    name: "Profile Polisher",
    description: "Update your profile or resume",
    icon: resolveChallengeIcon("update_profile"),
    iconType: "emoji",
    xpReward: 25,
    category: "profile",
    completed: false,
  },
  {
    id: "apply_job",
    name: "Job Application",
    description: "Apply to at least one job",
    icon: resolveChallengeIcon("apply_job"),
    iconType: "emoji",
    xpReward: 50,
    category: "job_search",
    completed: false,
  },
  {
    id: "map_skill",
    name: "Skill Mapper",
    description: "Map a gaming skill to a career skill",
    icon: resolveChallengeIcon("map_skill"),
    iconType: "emoji",
    xpReward: 30,
    category: "skill_building",
    completed: false,
  },
  {
    id: "practice_interview",
    name: "Interview Practice",
    description: "Complete a mock interview",
    icon: resolveChallengeIcon("practice_interview"),
    iconType: "emoji",
    xpReward: 75,
    category: "skill_building",
    completed: false,
  },
  {
    id: "explore_studio",
    name: "Studio Explorer",
    description: "Explore a new game studio",
    icon: resolveChallengeIcon("explore_studio"),
    iconType: "emoji",
    xpReward: 20,
    category: "engagement",
    completed: false,
  },
  {
    id: "interview_sprint",
    name: "Interview Sprint",
    description: "Complete an interview session",
    icon: resolveChallengeIcon("interview_sprint"),
    iconType: "emoji",
    xpReward: 75,
    category: "skill_building",
    completed: false,
  },
  {
    id: "skill_discovery",
    name: "Skill Discovery",
    description: "Map 2 new gaming skills",
    icon: resolveChallengeIcon("skill_discovery"),
    iconType: "emoji",
    xpReward: 40,
    category: "skill_building",
    completed: false,
  },
  {
    id: "network_builder",
    name: "Network Builder",
    description: "Research 3 gaming studios",
    icon: resolveChallengeIcon("network_builder"),
    iconType: "emoji",
    xpReward: 35,
    category: "engagement",
    completed: false,
  },
  {
    id: "portfolio_polish",
    name: "Portfolio Polish",
    description: "Update a portfolio project",
    icon: resolveChallengeIcon("portfolio_polish"),
    iconType: "emoji",
    xpReward: 45,
    category: "profile",
    completed: false,
  },
  {
    id: "ai_deep_dive",
    name: "AI Deep Dive",
    description: "Have a 5+ turn AI conversation",
    icon: resolveChallengeIcon("ai_deep_dive"),
    iconType: "emoji",
    xpReward: 60,
    category: "engagement",
    completed: false,
  },
];
