import { getGamificationAchievementIcon } from "@bao/shared/constants/gamification-icons";
import type { Achievement, GamificationStats } from "@bao/shared/types/gamification";

type AchievementDefinition = Omit<Achievement, "unlocked" | "unlockedAt">;

const resolveAchievementIcon = (achievementId: string): string =>
  getGamificationAchievementIcon(achievementId);

export const GAMIFICATION_STAT_KEYS: Array<keyof GamificationStats> = [
  "profileComplete",
  "skillsMapped",
  "portfolioItems",
  "jobApplications",
  "chatSessions",
  "resumesGenerated",
  "coverLettersGenerated",
  "savedJobs",
  "jobsSaved",
  "interviewScore",
  "dataExported",
  "earlyLogin",
  "totalTimeSpent",
  "featuresUsed",
  "dailyStreak",
  "weeklyProgress",
  "interviewsCompleted",
  "studiosExplored",
];

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  {
    id: "first_resume",
    name: "Getting Started",
    description: "Create your first resume",
    icon: resolveAchievementIcon("first_resume"),
    iconType: "emoji",
    category: "progress",
    xpReward: 50,
    requirements: { resumesGenerated: 1 },
    rarity: "common",
  },
  {
    id: "resume_master",
    name: "Resume Master",
    description: "Create 5 different resumes",
    icon: resolveAchievementIcon("resume_master"),
    iconType: "emoji",
    category: "milestone",
    xpReward: 200,
    requirements: { resumesGenerated: 5 },
    rarity: "rare",
  },
  {
    id: "portfolio_builder",
    name: "Portfolio Builder",
    description: "Add 3 projects to your portfolio",
    icon: resolveAchievementIcon("portfolio_builder"),
    iconType: "emoji",
    category: "progress",
    xpReward: 100,
    requirements: { portfolioItems: 3 },
    rarity: "common",
  },
  {
    id: "skill_mapper",
    name: "Skill Mapper",
    description: "Map 10 gaming skills to career skills",
    icon: resolveAchievementIcon("skill_mapper"),
    iconType: "emoji",
    category: "skill",
    xpReward: 150,
    requirements: { skillsMapped: 10 },
    rarity: "rare",
  },
  {
    id: "interview_ready",
    name: "Interview Ready",
    description: "Complete 5 mock interviews",
    icon: resolveAchievementIcon("interview_ready"),
    iconType: "emoji",
    category: "progress",
    xpReward: 250,
    requirements: { interviewsCompleted: 5 },
    rarity: "epic",
  },
  {
    id: "consistent_user",
    name: "Consistent User",
    description: "Maintain a 7-day streak",
    icon: resolveAchievementIcon("consistent_user"),
    iconType: "emoji",
    category: "special",
    xpReward: 300,
    requirements: { dailyStreak: 7 },
    rarity: "epic",
  },
  {
    id: "job_hunter",
    name: "Job Hunter",
    description: "Apply to 20 jobs",
    icon: resolveAchievementIcon("job_hunter"),
    iconType: "emoji",
    category: "progress",
    xpReward: 400,
    requirements: { jobApplications: 20 },
    rarity: "legendary",
  },
  {
    id: "explorer",
    name: "Studio Explorer",
    description: "Explore 10 different game studios",
    icon: resolveAchievementIcon("explorer"),
    iconType: "emoji",
    category: "progress",
    xpReward: 100,
    requirements: { studiosExplored: 10 },
    rarity: "common",
  },
  {
    id: "portfolio_pro",
    name: "Portfolio Pro",
    description: "Add 5 projects to your portfolio",
    icon: resolveAchievementIcon("portfolio_pro"),
    iconType: "emoji",
    category: "milestone",
    xpReward: 200,
    requirements: { portfolioItems: 5 },
    rarity: "rare",
  },
  {
    id: "interview_master",
    name: "Interview Master",
    description: "Complete 10 mock interviews",
    icon: resolveAchievementIcon("interview_master"),
    iconType: "emoji",
    category: "milestone",
    xpReward: 500,
    requirements: { interviewsCompleted: 10 },
    rarity: "epic",
  },
  {
    id: "skill_cartographer",
    name: "Skill Cartographer",
    description: "Map 20 skills to career paths",
    icon: resolveAchievementIcon("skill_cartographer"),
    iconType: "emoji",
    category: "skill",
    xpReward: 300,
    requirements: { skillsMapped: 20 },
    rarity: "rare",
  },
  {
    id: "studio_scholar",
    name: "Studio Scholar",
    description: "Explore 25 different game studios",
    icon: resolveAchievementIcon("studio_scholar"),
    iconType: "emoji",
    category: "progress",
    xpReward: 150,
    requirements: { studiosExplored: 25 },
    rarity: "rare",
  },
  {
    id: "ai_collaborator",
    name: "AI Collaborator",
    description: "Have 50 AI chat conversations",
    icon: resolveAchievementIcon("ai_collaborator"),
    iconType: "emoji",
    category: "special",
    xpReward: 250,
    requirements: { chatSessions: 50 },
    rarity: "rare",
  },
  {
    id: "cover_letter_crafter",
    name: "Cover Letter Crafter",
    description: "Generate 5 cover letters",
    icon: resolveAchievementIcon("cover_letter_crafter"),
    iconType: "emoji",
    category: "progress",
    xpReward: 200,
    requirements: { coverLettersGenerated: 5 },
    rarity: "rare",
  },
  {
    id: "job_hunter_elite",
    name: "Job Hunter Elite",
    description: "Save 50 jobs to your board",
    icon: resolveAchievementIcon("job_hunter_elite"),
    iconType: "emoji",
    category: "milestone",
    xpReward: 500,
    requirements: { jobsSaved: 50 },
    rarity: "epic",
  },
  {
    id: "perfect_score",
    name: "Perfect Score",
    description: "Score 90+ on a mock interview",
    icon: resolveAchievementIcon("perfect_score"),
    iconType: "emoji",
    category: "special",
    xpReward: 750,
    requirements: { interviewScore: 90 },
    rarity: "legendary",
  },
  {
    id: "streak_legend",
    name: "Streak Legend",
    description: "Maintain a 30-day activity streak",
    icon: resolveAchievementIcon("streak_legend"),
    iconType: "emoji",
    category: "special",
    xpReward: 1000,
    requirements: { dailyStreak: 30 },
    rarity: "legendary",
  },
  {
    id: "data_guardian",
    name: "Data Guardian",
    description: "Export your data for the first time",
    icon: resolveAchievementIcon("data_guardian"),
    iconType: "emoji",
    category: "progress",
    xpReward: 100,
    requirements: { dataExported: 1 },
    rarity: "common",
  },
  {
    id: "early_bird",
    name: "Early Bird",
    description: "Log in before 8 AM",
    icon: resolveAchievementIcon("early_bird"),
    iconType: "emoji",
    category: "special",
    xpReward: 50,
    requirements: { earlyLogin: 1 },
    rarity: "common",
  },
  {
    id: "completionist",
    name: "Completionist",
    description: "Fill out 100% of your profile",
    icon: resolveAchievementIcon("completionist"),
    iconType: "emoji",
    category: "milestone",
    xpReward: 1000,
    requirements: { profileComplete: 100 },
    rarity: "legendary",
  },
];
