/**
 * Biome ratchet additions for industry-best-practice UI/UX/wiring rules.
 *
 * Extracted from biome-softener-ratchet.ts to stay under the HB023 400-line
 * file ceiling. These predicates enforce the rules added in the 2026-07-21
 * lint-hardening pass: noMagicNumbers, noShoutyConstants, noCommonJs,
 * useThrowOnlyError, useExplicitLengthCheck, noDoneCallback,
 * noEmptyBlockStatements, noTemplateCurlyInString.
 *
 * noUndeclaredClasses and noUnusedClasses are intentionally NOT enforced:
 * they produce false positives on Tailwind/daisyUI utility classes (the rule
 * cannot resolve classes generated by the Tailwind compiler). Enforcing them
 * would require 268+ suppressions or a custom class allowlist that drifts from
 * the Tailwind config. The canonical fix is to wait for biome to support
 * Tailwind class resolution (tracked in
 * scripts/docs/biome-tailwind-incompatibility.md).
 */
import type { SoftenerJsonValue } from "./biome-softener-ratchet";
import type { ValidationViolation } from "./validation-helpers";
import { isSoftenerRecord, requireRuleError } from "./biome-softener-ratchet";

export const validateStyleAdditionsRatchet = (
  style: { [key: string]: SoftenerJsonValue },
  violations: ValidationViolation[],
  biomePath: string,
): void => {
  for (const ruleName of [
    "noShoutyConstants",
    "noCommonJs",
    "useThrowOnlyError",
    "useExplicitLengthCheck",
    "noDoneCallback",
  ] as const) {
    requireRuleError(style, ruleName, "linter.rules.style", violations, biomePath);
  }
  const magicNumbers = style.noMagicNumbers;
  const magicNumbersOk =
    magicNumbers === "error" || (isSoftenerRecord(magicNumbers) && magicNumbers.level === "error");
  if (!magicNumbersOk) {
    violations.push({
      filePath: biomePath,
      line: 1,
      message:
        'linter.rules.style.noMagicNumbers must be "error" (extract magic numbers to named constants).',
    });
  }
};

export const validateSuspiciousAdditionsRatchet = (
  suspicious: { [key: string]: SoftenerJsonValue },
  violations: ValidationViolation[],
  biomePath: string,
): void => {
  for (const ruleName of ["noEmptyBlockStatements", "noTemplateCurlyInString"] as const) {
    requireRuleError(suspicious, ruleName, "linter.rules.suspicious", violations, biomePath);
  }
};
