/**
 * Canonical API success/info messages used across server routes.
 * Single source of truth for user-facing message strings.
 */
export const API_MESSAGE_JOB_ALREADY_SAVED = "Job already saved";
export const API_MESSAGE_ALREADY_APPLIED = "Already applied to this job";
export const API_MESSAGE_JOB_REFRESH_COMPLETE = "Job refresh completed successfully";
export const API_MESSAGE_AUTH_DISABLED = "Auth disabled";
export const API_MESSAGE_API_KEY_ALREADY_CONFIGURED = "API key already configured";
export const API_MESSAGE_SAVE_API_KEY_ONCE = "Save this API key — it will not be shown again";
export const API_MESSAGE_AUTH_SETUP_TOKEN_REQUIRED =
  "Provide the setup token to initialize the first API key";
export const API_MESSAGE_INTERVIEW_SESSION_CREATED = "Interview session created";
export const API_MESSAGE_RESPONSE_RECORDED = "Response recorded";
export const API_MESSAGE_INTERVIEW_COMPLETED = "Interview completed";
export const API_MESSAGE_AI_NO_JOBS_FOR_MATCHING = "No jobs available for matching";
export const API_MESSAGE_JOB_MATCHING_COMPLETE = "Job matching complete";
export const API_MESSAGE_RESUME_ANALYSIS_COMPLETE = "Resume analysis complete";
export const API_MESSAGE_COVER_LETTER_GENERATED = "Cover letter generated successfully";
export const API_MESSAGE_COVER_LETTER_GENERATED_SAVED = "Cover letter generated and saved";
export const API_MESSAGE_COVER_LETTER_GENERATED_ONLY = "Cover letter generated";
export const API_MESSAGE_SKILL_ANALYSIS_COMPLETE = "AI skill analysis completed successfully";
export const API_MESSAGE_SKILL_MAPPING_DELETED = "Skill mapping deleted";
export const API_MESSAGE_AI_NO_PROVIDERS =
  "No AI providers configured. Please add API keys in settings.";
export const API_MESSAGE_CHALLENGE_COMPLETED = "Challenge completed!";
export const API_MESSAGE_STUDIO_DELETED = "Studio deleted";

/** WebSocket connection message for interview system. */
export const API_MESSAGE_WS_INTERVIEW_CONNECTED = "Connected to BaoBuildBuddy interview system";

/** Email response generated by automation. */
export const API_MESSAGE_EMAIL_RESPONSE_GENERATED = "Email response generated";

/** Email response generated and delivered by automation. */
export const API_MESSAGE_EMAIL_RESPONSE_DELIVERED = "Email response delivered";

/** Job application automation completed. */
export const API_MESSAGE_JOB_APPLICATION_AUTOMATION_COMPLETED =
  "Job application automation completed";
