import type {
  JobTaxonomyKeywordCategory,
  JobTaxonomyKeywordEntry,
  JobTaxonomySettings,
  StudioClassificationRule,
} from "../types/jobs-taxonomy";

const createKeywordEntry = (
  category: JobTaxonomyKeywordCategory,
  label: string,
  sortOrder: number,
  synonyms: readonly string[] = [],
): JobTaxonomyKeywordEntry => ({
  id: `${category}:${sortOrder}:${label
    .toLowerCase()
    .replaceAll(/\s+/g, "-")
    .replaceAll(/[^a-z0-9#+:/-]/g, "")}`,
  category,
  label,
  synonyms: [...synonyms],
  sortOrder,
  enabled: true,
});

const createStudioRule = (
  studioType: StudioClassificationRule["studioType"],
  keyword: string,
  sortOrder: number,
): StudioClassificationRule => ({
  id: `${studioType}:${sortOrder}:${keyword
    .toLowerCase()
    .replaceAll(/\s+/g, "-")
    .replaceAll(/[^a-z0-9/-]/g, "")}`,
  studioType,
  keyword,
  sortOrder,
  enabled: true,
});

export const DEFAULT_JOB_TAXONOMY_KEYWORDS: readonly JobTaxonomyKeywordEntry[] = [
  createKeywordEntry("remote-location", "remote", 0),
  createKeywordEntry("remote-location", "work from home", 1),
  createKeywordEntry("remote-location", "wfh", 2),
  createKeywordEntry("remote-location", "anywhere", 3),
  createKeywordEntry("hybrid-location", "hybrid", 0),
  createKeywordEntry("requirement", "C++", 0),
  createKeywordEntry("requirement", "C#", 1),
  createKeywordEntry("requirement", "Unity", 2),
  createKeywordEntry("requirement", "Unreal Engine", 3),
  createKeywordEntry("requirement", "Python", 4),
  createKeywordEntry("requirement", "Java", 5),
  createKeywordEntry("requirement", "JavaScript", 6),
  createKeywordEntry("requirement", "Graphics Programming", 7),
  createKeywordEntry("requirement", "Game Design", 8),
  createKeywordEntry("requirement", "Level Design", 9),
  createKeywordEntry("requirement", "3D Modeling", 10),
  createKeywordEntry("requirement", "Animation", 11),
  createKeywordEntry("requirement", "UI/UX", 12),
  createKeywordEntry("requirement", "Networking", 13),
  createKeywordEntry("requirement", "Multiplayer", 14),
  createKeywordEntry("requirement", "AI Programming", 15),
  createKeywordEntry("technology", "Unity", 0),
  createKeywordEntry("technology", "Unreal Engine", 1),
  createKeywordEntry("technology", "Godot", 2),
  createKeywordEntry("technology", "CryEngine", 3),
  createKeywordEntry("technology", "Blender", 4),
  createKeywordEntry("technology", "Maya", 5),
  createKeywordEntry("technology", "3ds Max", 6),
  createKeywordEntry("technology", "Substance Painter", 7),
  createKeywordEntry("technology", "ZBrush", 8),
  createKeywordEntry("technology", "Photoshop", 9),
  createKeywordEntry("technology", "Git", 10),
  createKeywordEntry("technology", "Perforce", 11),
  createKeywordEntry("technology", "Jira", 12),
  createKeywordEntry("technology", "C++", 13),
  createKeywordEntry("technology", "C#", 14),
  createKeywordEntry("technology", "Python", 15),
  createKeywordEntry("technology", "Lua", 16),
  createKeywordEntry("technology", "DirectX", 17),
  createKeywordEntry("technology", "OpenGL", 18),
  createKeywordEntry("technology", "Vulkan", 19),
  createKeywordEntry("technology", "Metal", 20),
  createKeywordEntry("technology", "AWS", 21),
  createKeywordEntry("technology", "Azure", 22),
  createKeywordEntry("technology", "Docker", 23),
  createKeywordEntry("technology", "Kubernetes", 24),
  createKeywordEntry("genre", "RPG", 0),
  createKeywordEntry("genre", "FPS", 1),
  createKeywordEntry("genre", "MMORPG", 2),
  createKeywordEntry("genre", "MOBA", 3),
  createKeywordEntry("genre", "Battle Royale", 4),
  createKeywordEntry("genre", "Strategy", 5),
  createKeywordEntry("genre", "Simulation", 6),
  createKeywordEntry("genre", "Sports", 7),
  createKeywordEntry("genre", "Racing", 8),
  createKeywordEntry("genre", "Horror", 9),
  createKeywordEntry("genre", "Platformer", 10),
  createKeywordEntry("genre", "Puzzle", 11),
  createKeywordEntry("platform", "PC", 0),
  createKeywordEntry("platform", "Console", 1),
  createKeywordEntry("platform", "Mobile", 2),
  createKeywordEntry("platform", "PlayStation", 3),
  createKeywordEntry("platform", "Xbox", 4),
  createKeywordEntry("platform", "Switch", 5),
  createKeywordEntry("platform", "Steam", 6),
  createKeywordEntry("platform", "VR", 7),
  createKeywordEntry("platform", "AR", 8),
  createKeywordEntry("platform", "Web", 9),
  createKeywordEntry("role", "Game Designer", 0),
  createKeywordEntry("role", "Level Designer", 1),
  createKeywordEntry("role", "Systems Designer", 2),
  createKeywordEntry("role", "Narrative Designer", 3),
  createKeywordEntry("role", "Quest Designer", 4),
  createKeywordEntry("role", "Combat Designer", 5),
  createKeywordEntry("role", "Economy Designer", 6),
  createKeywordEntry("role", "UI/UX Designer", 7),
  createKeywordEntry("role", "Gameplay Programmer", 8),
  createKeywordEntry("role", "Engine Programmer", 9),
  createKeywordEntry("role", "Graphics Programmer", 10),
  createKeywordEntry("role", "AI Programmer", 11),
  createKeywordEntry("role", "Network Programmer", 12),
  createKeywordEntry("role", "Tools Programmer", 13),
  createKeywordEntry("role", "Build Engineer", 14),
  createKeywordEntry("role", "Technical Artist", 15),
  createKeywordEntry("role", "Concept Artist", 16),
  createKeywordEntry("role", "3D Modeler", 17),
  createKeywordEntry("role", "Animator", 18),
  createKeywordEntry("role", "VFX Artist", 19),
  createKeywordEntry("role", "Environment Artist", 20),
  createKeywordEntry("role", "Character Artist", 21),
  createKeywordEntry("role", "Texture Artist", 22),
  createKeywordEntry("role", "Sound Designer", 23),
  createKeywordEntry("role", "Music Composer", 24),
  createKeywordEntry("role", "Audio Engineer", 25),
  createKeywordEntry("role", "Producer", 26),
  createKeywordEntry("role", "Associate Producer", 27),
  createKeywordEntry("role", "Executive Producer", 28),
  createKeywordEntry("role", "QA Tester", 29),
  createKeywordEntry("role", "QA Lead", 30),
  createKeywordEntry("role", "QA Automation Engineer", 31),
  createKeywordEntry("role", "Community Manager", 32),
  createKeywordEntry("role", "DevOps Engineer", 33),
  createKeywordEntry("role", "Data Analyst", 34),
  createKeywordEntry("role", "Live Ops Manager", 35),
  createKeywordEntry("role", "Monetization Designer", 36),
  createKeywordEntry("role", "Localization Specialist", 37),
  createKeywordEntry("role", "Art Director", 38),
  createKeywordEntry("role", "Creative Director", 39),
  createKeywordEntry("role", "Technical Director", 40),
  createKeywordEntry("role", "Game Director", 41),
  createKeywordEntry("role", "Studio Head", 42),
  createKeywordEntry("role", "Project Manager", 43),
] as const;

export const DEFAULT_STUDIO_CLASSIFICATION_RULES: readonly StudioClassificationRule[] = [
  createStudioRule("AAA", "riot", 0),
  createStudioRule("AAA", "epic", 1),
  createStudioRule("AAA", "blizzard", 2),
  createStudioRule("AAA", "electronic arts", 3),
  createStudioRule("AAA", "ea", 4),
  createStudioRule("AAA", "activision", 5),
  createStudioRule("AAA", "ubisoft", 6),
  createStudioRule("AAA", "rockstar", 7),
  createStudioRule("AAA", "bungie", 8),
  createStudioRule("AAA", "naughty dog", 9),
  createStudioRule("AAA", "insomniac", 10),
  createStudioRule("AAA", "respawn", 11),
  createStudioRule("AAA", "guerrilla", 12),
  createStudioRule("AAA", "treyarch", 13),
  createStudioRule("AAA", "sledgehammer", 14),
  createStudioRule("AAA", "infinity ward", 15),
  createStudioRule("AAA", "2k", 16),
  createStudioRule("AAA", "square enix", 17),
  createStudioRule("AAA", "obsidian", 18),
  createStudioRule("AAA", "gearbox", 19),
  createStudioRule("AAA", "playground games", 20),
  createStudioRule("AAA", "sucker punch", 21),
  createStudioRule("AAA", "arkane", 22),
  createStudioRule("AAA", "machinegames", 23),
  createStudioRule("AAA", "machine games", 24),
  createStudioRule("AAA", "cd projekt", 25),
  createStudioRule("AAA", "wargaming", 26),
  createStudioRule("AAA", "mojang", 27),
  createStudioRule("AAA", "firaxis", 28),
  createStudioRule("AAA", "avalanche", 29),
  createStudioRule("AAA", "amplitude", 30),
  createStudioRule("AAA", "cloud imperium", 31),
  createStudioRule("AAA", "cloud chamber", 32),
  createStudioRule("AAA", "netflix games", 33),
  createStudioRule("AAA", "lightspeed", 34),
  createStudioRule("AAA", "striking distance", 35),
  createStudioRule("AAA", "bandai namco", 36),
  createStudioRule("AAA", "capcom", 37),
  createStudioRule("AAA", "sega", 38),
  createStudioRule("AAA", "konami", 39),
  createStudioRule("AAA", "take-two", 40),
  createStudioRule("AAA", "take two", 41),
  createStudioRule("AAA", "bethesda", 42),
  createStudioRule("AAA", "larian", 43),
  createStudioRule("AAA", "double fine", 44),
  createStudioRule("AAA", "second dinner", 45),
  createStudioRule("AAA", "archetype entertainment", 46),
  createStudioRule("Mobile", "supercell", 0),
  createStudioRule("Mobile", "zynga", 1),
  createStudioRule("Mobile", "king", 2),
  createStudioRule("Mobile", "jam city", 3),
  createStudioRule("Mobile", "wildlife", 4),
  createStudioRule("Mobile", "playq", 5),
  createStudioRule("Mobile", "voodoo", 6),
  createStudioRule("Mobile", "niantic", 7),
  createStudioRule("Mobile", "pokemon", 8),
  createStudioRule("Mobile", "demiurge", 9),
  createStudioRule("VR/AR", "meta", 0),
  createStudioRule("VR/AR", "oculus", 1),
  createStudioRule("Platform", "valve", 0),
  createStudioRule("Platform", "unity", 1),
  createStudioRule("Platform", "unreal", 2),
  createStudioRule("Platform", "nvidia", 3),
  createStudioRule("Platform", "roblox", 4),
  createStudioRule("Platform", "discord", 5),
  createStudioRule("Esports", "esl", 0),
  createStudioRule("Esports", "faceit", 1),
  createStudioRule("Esports", "hitmarker", 2),
] as const;

export const DEFAULT_JOB_TAXONOMY_SETTINGS: JobTaxonomySettings = {
  keywords: [...DEFAULT_JOB_TAXONOMY_KEYWORDS],
  studioRules: [...DEFAULT_STUDIO_CLASSIFICATION_RULES],
};
