import type { Static } from "typebox";
export declare const userProfileUpdateBodySchema: import("typebox").TObject<{
    name: import("typebox").TOptional<import("typebox").TString>;
    email: import("typebox").TOptional<import("typebox").TString>;
    phone: import("typebox").TOptional<import("typebox").TString>;
    location: import("typebox").TOptional<import("typebox").TString>;
    website: import("typebox").TOptional<import("typebox").TString>;
    linkedin: import("typebox").TOptional<import("typebox").TString>;
    github: import("typebox").TOptional<import("typebox").TString>;
    summary: import("typebox").TOptional<import("typebox").TString>;
    currentRole: import("typebox").TOptional<import("typebox").TString>;
    currentCompany: import("typebox").TOptional<import("typebox").TString>;
    yearsExperience: import("typebox").TOptional<import("typebox").TNumber>;
    technicalSkills: import("typebox").TOptional<import("typebox").TArray<import("typebox").TString>>;
    softSkills: import("typebox").TOptional<import("typebox").TArray<import("typebox").TString>>;
    gamingExperience: import("typebox").TOptional<import("typebox").TRecord<"^.*$", import("typebox").TUnknown>>;
    careerGoals: import("typebox").TOptional<import("typebox").TRecord<"^.*$", import("typebox").TUnknown>>;
}>;
export type UserProfileUpdateRouteBody = Static<typeof userProfileUpdateBodySchema>;
export declare const userProfileResponseSchema: import("typebox").TObject<{
    id: import("typebox").TString;
    name: import("typebox").TString;
    email: import("typebox").TUnion<[import("typebox").TString, import("typebox").TNull]>;
    phone: import("typebox").TUnion<[import("typebox").TString, import("typebox").TNull]>;
    location: import("typebox").TUnion<[import("typebox").TString, import("typebox").TNull]>;
    website: import("typebox").TUnion<[import("typebox").TString, import("typebox").TNull]>;
    linkedin: import("typebox").TUnion<[import("typebox").TString, import("typebox").TNull]>;
    github: import("typebox").TUnion<[import("typebox").TString, import("typebox").TNull]>;
    summary: import("typebox").TUnion<[import("typebox").TString, import("typebox").TNull]>;
    currentRole: import("typebox").TUnion<[import("typebox").TString, import("typebox").TNull]>;
    currentCompany: import("typebox").TUnion<[import("typebox").TString, import("typebox").TNull]>;
    yearsExperience: import("typebox").TUnion<[import("typebox").TNumber, import("typebox").TNull]>;
    technicalSkills: import("typebox").TArray<import("typebox").TString>;
    softSkills: import("typebox").TArray<import("typebox").TString>;
    gamingExperience: import("typebox").TRecord<"^.*$", import("typebox").TUnknown>;
    careerGoals: import("typebox").TRecord<"^.*$", import("typebox").TUnknown>;
    createdAt: import("typebox").TString;
    updatedAt: import("typebox").TString;
}>;
