/**
 * Script-side numeric SSOT. Named consts only; noMagicNumbers stays error.
 * Values that exist in the shared package are assigned from there — the
 * shared package owns the definition, this module owns script-only extras.
 * Structured as assignments (not `export { … } from`) so noBarrelFile stays clean.
 */
import {
  HTTP_STATUS_NOT_FOUND,
  HTTP_STATUS_OK,
  HTTP_STATUS_UNPROCESSABLE_ENTITY,
} from "../../packages/shared/src/constants/http";
import {
  BYTES_KILO as SHARED_BYTES_KILO,
  BYTES_TWO_KILO as SHARED_BYTES_TWO_KILO,
  COUNT_EIGHT as SHARED_COUNT_EIGHT,
  COUNT_EIGHTEEN as SHARED_COUNT_EIGHTEEN,
  COUNT_FIFTEEN as SHARED_COUNT_FIFTEEN,
  COUNT_FIFTY as SHARED_COUNT_FIFTY,
  COUNT_FIVE as SHARED_COUNT_FIVE,
  COUNT_FIVE_HUNDRED as SHARED_COUNT_FIVE_HUNDRED,
  COUNT_FORTY as SHARED_COUNT_FORTY,
  COUNT_FORTY_FOUR as SHARED_COUNT_FORTY_FOUR,
  COUNT_FOUR as SHARED_COUNT_FOUR,
  COUNT_ONE_FIFTY as SHARED_COUNT_ONE_FIFTY,
  COUNT_ONE_TWENTY as SHARED_COUNT_ONE_TWENTY,
  COUNT_SEVEN as SHARED_COUNT_SEVEN,
  COUNT_SEVENTY as SHARED_COUNT_SEVENTY,
  COUNT_SIX as SHARED_COUNT_SIX,
  COUNT_SIXTEEN as SHARED_COUNT_SIXTEEN,
  COUNT_THIRTY as SHARED_COUNT_THIRTY,
  COUNT_THIRTY_FOUR as SHARED_COUNT_THIRTY_FOUR,
  COUNT_THIRTY_SIX as SHARED_COUNT_THIRTY_SIX,
  COUNT_THIRTY_TWO as SHARED_COUNT_THIRTY_TWO,
  COUNT_THREE as SHARED_COUNT_THREE,
  COUNT_TWELVE as SHARED_COUNT_TWELVE,
  COUNT_TWENTY as SHARED_COUNT_TWENTY,
  COUNT_TWENTY_EIGHT as SHARED_COUNT_TWENTY_EIGHT,
  COUNT_TWENTY_FIVE as SHARED_COUNT_TWENTY_FIVE,
  COUNT_TWENTY_TWO as SHARED_COUNT_TWENTY_TWO,
  COUNT_TWO as SHARED_COUNT_TWO,
  COUNT_TWO_FIFTY as SHARED_COUNT_TWO_FIFTY,
  COUNT_TWO_FORTY as SHARED_COUNT_TWO_FORTY,
  MS_FIVE_SECONDS as SHARED_MS_FIVE_SECONDS,
  MS_ONE_AND_EIGHT_SECONDS as SHARED_MS_ONE_AND_EIGHT_SECONDS,
  MS_ONE_AND_HALF_SECONDS as SHARED_MS_ONE_AND_HALF_SECONDS,
  MS_TEN_SECONDS as SHARED_MS_TEN_SECONDS,
  MS_THIRTY_SECONDS as SHARED_MS_THIRTY_SECONDS,
  MS_THREE_SECONDS as SHARED_MS_THREE_SECONDS,
  MS_TWO_AND_HALF_SECONDS as SHARED_MS_TWO_AND_HALF_SECONDS,
  MS_TWO_MINUTES as SHARED_MS_TWO_MINUTES,
  MS_TWO_SECONDS as SHARED_MS_TWO_SECONDS,
  PERCENT_HIGH as SHARED_PERCENT_HIGH,
  PERCENT_LOW as SHARED_PERCENT_LOW,
  PERCENT_MAX as SHARED_PERCENT_MAX,
  PERCENT_MID as SHARED_PERCENT_MID,
  RATIO_HALF as SHARED_RATIO_HALF,
  RATIO_SEVEN_TENTHS as SHARED_RATIO_SEVEN_TENTHS,
} from "../../packages/shared/src/constants/numeric";

export const HTTP_OK = HTTP_STATUS_OK;
export const HTTP_NOT_FOUND = HTTP_STATUS_NOT_FOUND;
export const HTTP_UNPROCESSABLE = HTTP_STATUS_UNPROCESSABLE_ENTITY;

export const PERCENT_MAX = SHARED_PERCENT_MAX;
export const PERCENT_HIGH = SHARED_PERCENT_HIGH;
export const PERCENT_MID = SHARED_PERCENT_MID;
export const PERCENT_LOW = SHARED_PERCENT_LOW;
export const MS_TWO_SECONDS = SHARED_MS_TWO_SECONDS;
export const MS_ONE_AND_HALF_SECONDS = SHARED_MS_ONE_AND_HALF_SECONDS;
export const MS_ONE_AND_EIGHT_SECONDS = SHARED_MS_ONE_AND_EIGHT_SECONDS;
export const MS_TWO_AND_HALF_SECONDS = SHARED_MS_TWO_AND_HALF_SECONDS;
export const MS_THREE_SECONDS = SHARED_MS_THREE_SECONDS;
export const MS_FIVE_SECONDS = SHARED_MS_FIVE_SECONDS;
export const MS_TEN_SECONDS = SHARED_MS_TEN_SECONDS;
export const MS_THIRTY_SECONDS = SHARED_MS_THIRTY_SECONDS;
export const MS_TWO_MINUTES = SHARED_MS_TWO_MINUTES;
export const COUNT_TWO = SHARED_COUNT_TWO;
export const COUNT_THREE = SHARED_COUNT_THREE;
export const COUNT_FOUR = SHARED_COUNT_FOUR;
export const COUNT_FIVE = SHARED_COUNT_FIVE;
export const COUNT_SIX = SHARED_COUNT_SIX;
export const COUNT_SEVEN = SHARED_COUNT_SEVEN;
export const COUNT_EIGHT = SHARED_COUNT_EIGHT;
export const COUNT_TWELVE = SHARED_COUNT_TWELVE;
export const COUNT_FIFTEEN = SHARED_COUNT_FIFTEEN;
export const COUNT_SIXTEEN = SHARED_COUNT_SIXTEEN;
export const COUNT_EIGHTEEN = SHARED_COUNT_EIGHTEEN;
export const COUNT_TWENTY = SHARED_COUNT_TWENTY;
export const COUNT_TWENTY_TWO = SHARED_COUNT_TWENTY_TWO;
export const COUNT_TWENTY_FIVE = SHARED_COUNT_TWENTY_FIVE;
export const COUNT_TWENTY_EIGHT = SHARED_COUNT_TWENTY_EIGHT;
export const COUNT_THIRTY = SHARED_COUNT_THIRTY;
export const COUNT_THIRTY_TWO = SHARED_COUNT_THIRTY_TWO;
export const COUNT_THIRTY_FOUR = SHARED_COUNT_THIRTY_FOUR;
export const COUNT_THIRTY_SIX = SHARED_COUNT_THIRTY_SIX;
export const COUNT_FORTY = SHARED_COUNT_FORTY;
export const COUNT_FORTY_FOUR = SHARED_COUNT_FORTY_FOUR;
export const COUNT_FIFTY = SHARED_COUNT_FIFTY;
export const COUNT_SEVENTY = SHARED_COUNT_SEVENTY;
export const COUNT_ONE_TWENTY = SHARED_COUNT_ONE_TWENTY;
export const COUNT_ONE_FIFTY = SHARED_COUNT_ONE_FIFTY;
export const COUNT_TWO_FORTY = SHARED_COUNT_TWO_FORTY;
export const COUNT_TWO_FIFTY = SHARED_COUNT_TWO_FIFTY;
export const COUNT_FIVE_HUNDRED = SHARED_COUNT_FIVE_HUNDRED;
export const BYTES_KILO = SHARED_BYTES_KILO;
export const BYTES_TWO_KILO = SHARED_BYTES_TWO_KILO;
export const RATIO_HALF = SHARED_RATIO_HALF;
export const RATIO_SEVEN_TENTHS = SHARED_RATIO_SEVEN_TENTHS;

export const MS_TWO_HUNDRED = 200;
export const MS_THREE_HUNDRED = 300;
export const MS_FOUR_HUNDRED = 400;
export const MS_SIX_HUNDRED = 600;
export const MS_SEVEN_HUNDRED = 700;
export const MS_EIGHT_HUNDRED = 800;
export const MS_NINE_HUNDRED = 900;
export const MS_SECOND = 1000;
export const BYTES_ONE_KILO_MIN = 1000;
export const MS_ONE_ONE_HUNDRED = 1_100;
export const MS_ONE_TWO_HUNDRED = 1_200;
export const MS_ONE_FOUR_HUNDRED = 1_400;
export const MS_FOUR_SECONDS = 4_000;
export const MS_EIGHT_SECONDS = 8_000;
export const MS_TWELVE_SECONDS = 12_000;
export const MS_MINUTE = 60_000;
export const MS_FORTY_FIVE_SECONDS = 45_000;
export const MS_SIXTY_SECONDS = 60_000;

export const VIEWPORT_WIDTH_DESKTOP = 1440;
export const VIEWPORT_HEIGHT_DESKTOP = 900;
export const VIEWPORT_WIDTH_MOBILE_PROOF = 390;
export const VIEWPORT_HEIGHT_MOBILE_PROOF = 844;

/** Owner read/write, group read, other read (`chmod 644`). */
export const FILE_MODE_RW_R_R = 0o644;
/** Owner read/write/execute, group read/execute, other read/execute (`chmod 755`). */
export const FILE_MODE_RWX_RX_RX = 0o755;
