export const GAMING_JOB_TITLES = [
  "Game Designer",
  "Senior Game Designer",
  "Lead Game Designer",
  "Principal Game Designer",
  "Gameplay Programmer",
  "Gameplay Engineer",
  "Engine Programmer",
  "Graphics Programmer",
  "AI Programmer",
  "Physics Programmer",
  "Network Programmer",
  "Tools Programmer",
  "Build Engineer",
  "DevOps Engineer",
  "Technical Designer",
  "Level Designer",
  "Systems Designer",
  "Combat Designer",
  "Economy Designer",
  "Content Designer",
  "Narrative Designer",
  "Quest Designer",
  "UI/UX Designer",
  "UI Designer",
  "UX Designer",
  "3D Artist",
  "Environment Artist",
  "Character Artist",
  "Concept Artist",
  "Technical Artist",
  "VFX Artist",
  "Animation Programmer",
  "Animator",
  "Character Animator",
  "Rigging Artist",
  "Lighting Artist",
  "Audio Designer",
  "Sound Designer",
  "Composer",
  "Audio Programmer",
  "Producer",
  "Associate Producer",
  "Senior Producer",
  "Executive Producer",
  "Product Manager",
  "Project Manager",
  "QA Tester",
  "QA Lead",
  "QA Manager",
  "QA Analyst",
  "Automation Engineer",
  "Live Ops Manager",
  "Community Manager",
  "Writer",
  "Narrative Lead",
  "Creative Director",
  "Art Director",
  "Technical Director",
  "Studio Head",
  "Game Director",
  "Engineering Manager",
  "Backend Engineer",
  "Full Stack Engineer",
  "Data Engineer",
  "Data Analyst",
  "Analytics Engineer",
  "Machine Learning Engineer",
  "Security Engineer",
  "Platform Engineer",
  "Release Manager",
  "Localization Manager",
  "Marketing Manager",
  "User Researcher",
];

export const GAMING_TITLES = [
  {
    title: "Elden Ring",
    developer: "FromSoftware",
    genres: ["Action RPG", "Souls-like", "Open World"],
    platforms: ["PC", "PlayStation", "Xbox"],
    skills: ["C++", "Boss Design", "Level Design", "Combat Systems", "Open World Design"],
  },
  {
    title: "Baldur's Gate 3",
    developer: "Larian Studios",
    genres: ["RPG", "CRPG", "Turn-based Strategy"],
    platforms: ["PC", "PlayStation", "Xbox"],
    skills: [
      "Proprietary Engine",
      "RPG Systems",
      "Narrative Design",
      "D&D 5e",
      "Cinematics",
      "Motion Capture",
    ],
  },
  {
    title: "The Last of Us Part II",
    developer: "Naughty Dog",
    genres: ["Action-Adventure", "Survival", "Third-Person"],
    platforms: ["PlayStation"],
    skills: [
      "C++",
      "Proprietary Engine",
      "Narrative Design",
      "Animation",
      "AI Programming",
      "Stealth Systems",
    ],
  },
  {
    title: "Genshin Impact",
    developer: "miHoYo",
    genres: ["Action RPG", "Open World", "Gacha"],
    platforms: ["PC", "Mobile", "PlayStation"],
    skills: [
      "Unity",
      "C#",
      "Live Service",
      "Mobile Optimization",
      "Gacha Systems",
      "Anime Art Style",
    ],
  },
  {
    title: "Fortnite",
    developer: "Epic Games",
    genres: ["Battle Royale", "Shooter", "Building"],
    platforms: ["PC", "Console", "Mobile"],
    skills: [
      "Unreal Engine",
      "C++",
      "Networking",
      "Live Service",
      "Backend Systems",
      "Cross-platform",
    ],
  },
  {
    title: "Apex Legends",
    developer: "Respawn Entertainment",
    genres: ["Battle Royale", "FPS", "Hero Shooter"],
    platforms: ["PC", "Console"],
    skills: ["Source Engine", "C++", "FPS Design", "Hero Abilities", "Networking", "Live Service"],
  },
  {
    title: "League of Legends",
    developer: "Riot Games",
    genres: ["MOBA", "Competitive", "Strategy"],
    platforms: ["PC"],
    skills: ["C++", "C#", "MOBA Design", "Champion Design", "Competitive Balance", "Live Service"],
  },
  {
    title: "Valorant",
    developer: "Riot Games",
    genres: ["FPS", "Tactical Shooter", "Competitive"],
    platforms: ["PC"],
    skills: ["C++", "C#", "FPS Design", "Agent Abilities", "Anti-cheat", "Competitive Systems"],
  },
  {
    title: "Helldivers 2",
    developer: "Arrowhead Game Studios",
    genres: ["Third-Person Shooter", "Co-op", "Action"],
    platforms: ["PC", "PlayStation"],
    skills: ["Autodesk Stingray", "C++", "Co-op Systems", "Physics", "Procedural Generation"],
  },
  {
    title: "Hades",
    developer: "Supergiant Games",
    genres: ["Roguelike", "Action", "Indie"],
    platforms: ["PC", "Console"],
    skills: ["Proprietary Engine", "C++", "Roguelike Design", "Narrative Systems", "Art Direction"],
  },
  {
    title: "God of War Ragnarök",
    developer: "Santa Monica Studio",
    genres: ["Action-Adventure", "Hack and Slash"],
    platforms: ["PlayStation"],
    skills: [
      "C++",
      "Proprietary Engine",
      "Combat Systems",
      "Animation",
      "Cinematics",
      "Norse Mythology",
    ],
  },
  {
    title: "Cyberpunk 2077",
    developer: "CD Projekt RED",
    genres: ["RPG", "Action", "Open World"],
    platforms: ["PC", "Console"],
    skills: ["REDengine", "C++", "Open World", "RPG Systems", "Quest Design", "Dialogue Systems"],
  },
  {
    title: "Minecraft",
    developer: "Mojang",
    genres: ["Sandbox", "Survival", "Creative"],
    platforms: ["PC", "Console", "Mobile"],
    skills: [
      "Java",
      "C++",
      "Procedural Generation",
      "Voxel Rendering",
      "Multiplayer",
      "Modding Support",
    ],
  },
  {
    title: "Counter-Strike 2",
    developer: "Valve",
    genres: ["FPS", "Tactical Shooter", "Competitive"],
    platforms: ["PC"],
    skills: [
      "Source 2",
      "C++",
      "Competitive FPS",
      "Weapon Design",
      "Map Design",
      "Economy Systems",
    ],
  },
  {
    title: "Spider-Man 2",
    developer: "Insomniac Games",
    genres: ["Action-Adventure", "Superhero", "Open World"],
    platforms: ["PlayStation"],
    skills: [
      "Proprietary Engine",
      "C++",
      "Traversal Systems",
      "Combat Design",
      "Open World",
      "Web-swinging Physics",
    ],
  },
  {
    title: "Destiny 2",
    developer: "Bungie",
    genres: ["FPS", "Looter Shooter", "MMO"],
    platforms: ["PC", "Console"],
    skills: ["Tiger Engine", "C++", "Live Service", "Loot Systems", "Raid Design", "Networking"],
  },
];

export const LOCATION_HUBS = [
  "Los Angeles, CA",
  "San Francisco, CA",
  "Seattle, WA",
  "Austin, TX",
  "New York, NY",
  "Boston, MA",
  "Montreal, Canada",
  "Vancouver, Canada",
  "Toronto, Canada",
  "London, UK",
  "Cambridge, UK",
  "Stockholm, Sweden",
  "Helsinki, Finland",
  "Paris, France",
  "Copenhagen, Denmark",
  "Berlin, Germany",
  "Warsaw, Poland",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Seoul, South Korea",
  "Shanghai, China",
  "Shenzhen, China",
  "Singapore",
  "Melbourne, Australia",
  "Sydney, Australia",
  "Amsterdam, Netherlands",
  "Dublin, Ireland",
  "Kyiv, Ukraine",
  "Prague, Czech Republic",
  "Barcelona, Spain",
];
