export const SEED_STUDIOS = [
  {
    id: "riot-games",
    name: "Riot Games",
    logo: null,
    website: "https://www.riotgames.com",
    location: "Los Angeles, CA",
    size: "1000+",
    type: "AAA",
    description:
      "Developer of League of Legends, Valorant, and Teamfight Tactics with a focus on competitive multiplayer games.",
    games: ["League of Legends", "Valorant", "Teamfight Tactics", "Legends of Runeterra"],
    technologies: ["C++", "C#", "Python", "Proprietary Engine", "AWS"],
    culture: {
      workStyle: "hybrid",
      benefits: [
        "Competitive salary",
        "Health insurance",
        "401k matching",
        "Unlimited PTO",
        "Wellness programs",
      ],
      diversity: "Strong commitment to diversity and inclusion with employee resource groups",
    },
    interviewStyle:
      "Technical assessments, portfolio review, behavioral interviews, and team fit evaluation",
    remoteWork: true,
  },
  {
    id: "electronic-arts",
    name: "Electronic Arts",
    logo: null,
    website: "https://www.ea.com",
    location: "Redwood City, CA",
    size: "1000+",
    type: "AAA",
    description:
      "One of the largest gaming companies worldwide, known for sports games and major franchises.",
    games: ["FIFA", "Madden NFL", "Apex Legends", "The Sims", "Battlefield", "Dragon Age"],
    technologies: ["Frostbite Engine", "Unreal Engine", "C++", "C#", "Python"],
    culture: {
      workStyle: "hybrid",
      benefits: [
        "Comprehensive health coverage",
        "Stock options",
        "Game discounts",
        "Professional development",
      ],
      diversity: "Diversity & Inclusion council with various ERGs",
    },
    interviewStyle:
      "Multi-stage process with technical tests, portfolio reviews, and cultural fit assessments",
    remoteWork: true,
  },
  {
    id: "activision-blizzard",
    name: "Activision Blizzard",
    logo: null,
    website: "https://www.activisionblizzard.com",
    location: "Santa Monica, CA",
    size: "1000+",
    type: "AAA",
    description:
      "Major publisher behind Call of Duty, World of Warcraft, Overwatch, and Diablo franchises.",
    games: [
      "Call of Duty",
      "World of Warcraft",
      "Overwatch",
      "Diablo",
      "Hearthstone",
      "Candy Crush",
    ],
    technologies: ["IW Engine", "Proprietary Engines", "C++", "C#", "Python"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Health benefits", "401k", "Game discounts", "Fitness reimbursement"],
      diversity: "Working to improve workplace culture with updated diversity initiatives",
    },
    interviewStyle: "Technical screening, on-site interviews, and portfolio presentation",
    remoteWork: true,
  },
  {
    id: "ubisoft",
    name: "Ubisoft",
    logo: null,
    website: "https://www.ubisoft.com",
    location: "Paris, France / Montreal, Canada",
    size: "1000+",
    type: "AAA",
    description:
      "French gaming giant known for open-world games and the Assassin's Creed franchise.",
    games: ["Assassin's Creed", "Far Cry", "Rainbow Six Siege", "Watch Dogs", "The Division"],
    technologies: ["Snowdrop Engine", "AnvilNext", "Dunia Engine", "C++", "Python"],
    culture: {
      workStyle: "hybrid",
      benefits: [
        "International opportunities",
        "Relocation support",
        "Health coverage",
        "Game library access",
      ],
      diversity: "Global diversity programs across all studios",
    },
    interviewStyle: "Portfolio review, technical tests, and multiple interview rounds",
    remoteWork: true,
  },
  {
    id: "epic-games",
    name: "Epic Games",
    logo: null,
    website: "https://www.epicgames.com",
    location: "Cary, NC",
    size: "1000+",
    type: "AAA",
    description:
      "Creator of Fortnite and Unreal Engine, one of the most influential companies in gaming technology.",
    games: ["Fortnite", "Gears of War", "Unreal Tournament", "Rocket League"],
    technologies: ["Unreal Engine", "C++", "Python", "Cloud services"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Generous PTO", "Health benefits", "401k matching", "Game library"],
      diversity: "Commitment to creating inclusive gaming experiences",
    },
    interviewStyle:
      "Technical deep dives, engine knowledge assessment, and team collaboration evaluation",
    remoteWork: true,
  },
  {
    id: "naughty-dog",
    name: "Naughty Dog",
    logo: null,
    website: "https://www.naughtydog.com",
    location: "Santa Monica, CA",
    size: "1000+",
    type: "AAA",
    description: "Sony's premier studio known for narrative-driven, technically impressive games.",
    games: ["The Last of Us", "Uncharted", "Jak and Daxter", "Crash Bandicoot"],
    technologies: ["Proprietary Engine", "C++", "Python", "Motion capture"],
    culture: {
      workStyle: "on-site",
      benefits: [
        "PlayStation benefits",
        "Health coverage",
        "Relocation assistance",
        "Creative environment",
      ],
      diversity: "Focus on authentic storytelling and diverse representation",
    },
    interviewStyle: "Rigorous portfolio review, technical assessments, and cultural fit evaluation",
    remoteWork: false,
  },
  {
    id: "cd-projekt-red",
    name: "CD Projekt RED",
    logo: null,
    website: "https://www.cdprojektred.com",
    location: "Warsaw, Poland",
    size: "1000+",
    type: "AAA",
    description: "Polish studio famous for The Witcher series and Cyberpunk 2077.",
    games: ["The Witcher 3", "Cyberpunk 2077", "Gwent", "The Witcher 2"],
    technologies: ["REDengine", "Unreal Engine 5", "C++", "Python"],
    culture: {
      workStyle: "hybrid",
      benefits: [
        "Competitive salary for region",
        "Health insurance",
        "Game library",
        "Relocation packages",
      ],
      diversity: "Growing focus on work-life balance and team wellbeing",
    },
    interviewStyle: "Portfolio review, technical tests, and passion for RPGs",
    remoteWork: true,
  },
  {
    id: "respawn-entertainment",
    name: "Respawn Entertainment",
    logo: null,
    website: "https://www.respawn.com",
    location: "Los Angeles, CA",
    size: "1000+",
    type: "AAA",
    description: "EA studio behind Apex Legends and Star Wars Jedi series.",
    games: [
      "Apex Legends",
      "Star Wars Jedi: Fallen Order",
      "Star Wars Jedi: Survivor",
      "Titanfall",
    ],
    technologies: ["Source Engine", "Unreal Engine", "C++", "C#"],
    culture: {
      workStyle: "hybrid",
      benefits: ["EA benefits package", "Health coverage", "Game discounts", "Flexible work"],
      diversity: "Inclusive hiring practices and diverse teams",
    },
    interviewStyle: "Technical screening, design challenges, and team interviews",
    remoteWork: true,
  },
  {
    id: "valve-corporation",
    name: "Valve Corporation",
    logo: null,
    website: "https://www.valvesoftware.com",
    location: "Bellevue, WA",
    size: "1000+",
    type: "AAA",
    description: "Creator of Steam, Half-Life, Portal, and maintains CS:GO and Dota 2.",
    games: ["Half-Life", "Counter-Strike", "Dota 2", "Portal", "Team Fortress 2", "Steam Deck"],
    technologies: ["Source 2 Engine", "C++", "Python", "Proprietary tools"],
    culture: {
      workStyle: "on-site",
      benefits: [
        "Flat organizational structure",
        "Top-tier compensation",
        "Health benefits",
        "Creative freedom",
      ],
      diversity: "Selective hiring with focus on autonomy and innovation",
    },
    interviewStyle:
      "Extremely rigorous multi-day interviews with technical and cultural assessments",
    remoteWork: false,
  },
  {
    id: "unity-technologies",
    name: "Unity Technologies",
    logo: null,
    website: "https://unity.com",
    location: "San Francisco, CA",
    size: "200-999",
    type: "Mid-size",
    description:
      "Developer of the Unity game engine, one of the most popular game development platforms.",
    games: ["Unity Engine", "Unity Asset Store", "Unity Cloud"],
    technologies: ["Unity Engine", "C#", "C++", "Cloud infrastructure"],
    culture: {
      workStyle: "remote-friendly",
      benefits: ["Remote work options", "Health benefits", "Stock options", "Learning budget"],
      diversity: "Global workforce with strong diversity initiatives",
    },
    interviewStyle: "Technical assessment focused on engine knowledge and problem-solving",
    remoteWork: true,
  },
  {
    id: "supercell",
    name: "Supercell",
    logo: null,
    website: "https://supercell.com",
    location: "Helsinki, Finland",
    size: "200-999",
    type: "Mid-size",
    description: "Finnish mobile gaming giant behind Clash of Clans and Brawl Stars.",
    games: ["Clash of Clans", "Clash Royale", "Brawl Stars", "Hay Day", "Boom Beach"],
    technologies: ["Proprietary Engine", "C++", "Python", "Mobile technologies"],
    culture: {
      workStyle: "on-site",
      benefits: [
        "Exceptional compensation",
        "Profit sharing",
        "Health benefits",
        "Small team autonomy",
      ],
      diversity: "Small teams with high autonomy and creative freedom",
    },
    interviewStyle: "Focus on team fit, autonomy, and creative vision",
    remoteWork: false,
  },
  {
    id: "king",
    name: "King",
    logo: null,
    website: "https://king.com",
    location: "Stockholm, Sweden",
    size: "200-999",
    type: "Mid-size",
    description: "Mobile gaming company owned by Activision Blizzard, famous for Candy Crush.",
    games: ["Candy Crush Saga", "Candy Crush Soda", "Farm Heroes", "Bubble Witch"],
    technologies: ["Proprietary Engine", "C++", "Mobile SDKs", "Analytics platforms"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Activision Blizzard benefits", "Health coverage", "Game development resources"],
      diversity: "Focus on data-driven development and player engagement",
    },
    interviewStyle: "Analytics-focused interviews with technical and design assessments",
    remoteWork: true,
  },
  {
    id: "mihoyo",
    name: "miHoYo/HoYoverse",
    logo: null,
    website: "https://www.hoyoverse.com",
    location: "Shanghai, China",
    size: "1000+",
    type: "AAA",
    description:
      "Chinese developer of Genshin Impact and Honkai series, known for anime-style games.",
    games: ["Genshin Impact", "Honkai Star Rail", "Honkai Impact 3rd", "Zenless Zone Zero"],
    technologies: ["Unity Engine", "Proprietary tools", "C++", "C#"],
    culture: {
      workStyle: "on-site",
      benefits: ["Competitive compensation", "Health benefits", "Game development culture"],
      diversity: "Rapidly growing with global expansion",
    },
    interviewStyle: "Portfolio review with focus on anime art style and live service experience",
    remoteWork: false,
  },
  {
    id: "larian-studios",
    name: "Larian Studios",
    logo: null,
    website: "https://larian.com",
    location: "Ghent, Belgium",
    size: "200-999",
    type: "Mid-size",
    description: "Independent RPG developer behind Baldur's Gate 3 and Divinity series.",
    games: ["Baldur's Gate 3", "Divinity: Original Sin 2", "Divinity: Original Sin"],
    technologies: ["Proprietary Engine", "C++", "Python", "Motion capture"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Creative freedom", "Health coverage", "International studios", "Passion-driven"],
      diversity: "Independent studio with strong creative vision",
    },
    interviewStyle: "Portfolio review focused on RPG experience and D&D knowledge",
    remoteWork: true,
  },
  {
    id: "fromsoftware",
    name: "FromSoftware",
    logo: null,
    website: "https://www.fromsoftware.jp",
    location: "Tokyo, Japan",
    size: "1000+",
    type: "AAA",
    description:
      "Japanese studio renowned for challenging action RPGs like Dark Souls and Elden Ring.",
    games: ["Elden Ring", "Dark Souls", "Bloodborne", "Sekiro: Shadows Die Twice", "Armored Core"],
    technologies: ["Proprietary Engine", "C++", "Japanese development tools"],
    culture: {
      workStyle: "on-site",
      benefits: ["Japanese employment benefits", "Health coverage", "Creative environment"],
      diversity: "Traditional Japanese game development culture",
    },
    interviewStyle: "Focus on technical skills and understanding of challenging game design",
    remoteWork: false,
  },
  {
    id: "rockstar-games",
    name: "Rockstar Games",
    logo: null,
    website: "https://www.rockstargames.com",
    location: "New York, NY",
    size: "1000+",
    type: "AAA",
    description:
      "Developer of Grand Theft Auto and Red Dead Redemption, known for massive open worlds.",
    games: ["Grand Theft Auto V", "Red Dead Redemption 2", "GTA Online", "Bully", "Max Payne"],
    technologies: ["RAGE Engine", "C++", "Proprietary tools"],
    culture: {
      workStyle: "on-site",
      benefits: ["Competitive compensation", "Health benefits", "Rockstar culture"],
      diversity: "Known for intensive development cycles",
    },
    interviewStyle: "Rigorous technical assessment and portfolio review",
    remoteWork: false,
  },
  {
    id: "bungie",
    name: "Bungie",
    logo: null,
    website: "https://www.bungie.net",
    location: "Bellevue, WA",
    size: "1000+",
    type: "AAA",
    description: "Independent studio known for Destiny and the original Halo series.",
    games: ["Destiny 2", "Destiny", "Halo series", "Marathon (upcoming)"],
    technologies: ["Tiger Engine", "C++", "Python", "Live service infrastructure"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Health benefits", "Stock options", "Generous PTO", "Game library"],
      diversity: "Strong focus on player community and inclusive culture",
    },
    interviewStyle: "Technical assessments with focus on live service and shooter experience",
    remoteWork: true,
  },
  {
    id: "kojima-productions",
    name: "Kojima Productions",
    logo: null,
    website: "https://www.kojimaproductions.jp",
    location: "Tokyo, Japan",
    size: "200-999",
    type: "Mid-size",
    description:
      "Hideo Kojima's independent studio known for innovative storytelling and gameplay.",
    games: ["Death Stranding", "Death Stranding 2", "Metal Gear Solid (legacy)"],
    technologies: ["Decima Engine", "C++", "Motion capture", "Proprietary tools"],
    culture: {
      workStyle: "on-site",
      benefits: ["Creative environment", "Health benefits", "Film industry connections"],
      diversity: "Auteur-driven development with cinematic focus",
    },
    interviewStyle: "Focus on creative vision, cinematic experience, and technical excellence",
    remoteWork: false,
  },
  {
    id: "insomniac-games",
    name: "Insomniac Games",
    logo: null,
    website: "https://insomniac.games",
    location: "Burbank, CA",
    size: "1000+",
    type: "AAA",
    description: "Sony studio famous for Spider-Man and Ratchet & Clank franchises.",
    games: ["Marvel's Spider-Man", "Ratchet & Clank", "Resistance", "Sunset Overdrive"],
    technologies: ["Proprietary Engine", "C++", "Python", "PlayStation SDKs"],
    culture: {
      workStyle: "hybrid",
      benefits: ["PlayStation benefits", "Health coverage", "Work-life balance focus"],
      diversity: "Known for positive workplace culture and employee satisfaction",
    },
    interviewStyle: "Portfolio review, technical tests, and cultural fit assessment",
    remoteWork: true,
  },
  {
    id: "obsidian-entertainment",
    name: "Obsidian Entertainment",
    logo: null,
    website: "https://www.obsidian.net",
    location: "Irvine, CA",
    size: "1000+",
    type: "AAA",
    description: "Xbox studio specializing in story-rich RPGs like The Outer Worlds and Avowed.",
    games: ["The Outer Worlds", "Avowed", "Grounded", "Pillars of Eternity", "Fallout: New Vegas"],
    technologies: ["Unreal Engine", "Unity", "C++", "C#"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "Health coverage", "Game library", "Xbox perks"],
      diversity: "Focus on narrative-driven experiences and player choice",
    },
    interviewStyle: "RPG knowledge assessment, writing tests, and technical evaluation",
    remoteWork: true,
  },
  {
    id: "remedy-entertainment",
    name: "Remedy Entertainment",
    logo: null,
    website: "https://www.remedygames.com",
    location: "Espoo, Finland",
    size: "200-999",
    type: "Mid-size",
    description: "Finnish studio known for cinematic action games like Alan Wake and Control.",
    games: ["Control", "Alan Wake 2", "Quantum Break", "Max Payne"],
    technologies: ["Northlight Engine", "C++", "Python", "Motion capture"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Finnish benefits", "Health coverage", "Creative environment"],
      diversity: "Focus on cinematic storytelling and innovative gameplay",
    },
    interviewStyle: "Portfolio review with emphasis on cinematic experience and technical skills",
    remoteWork: true,
  },
  {
    id: "keywords-studios",
    name: "Keywords Studios",
    logo: null,
    website: "https://www.keywordsstudios.com",
    location: "Dublin, Ireland",
    size: "500+",
    type: "Services",
    description:
      "Global services provider for game development, QA, localization, and co-development.",
    games: ["Services for AAA publishers", "QA", "Localization", "Art services"],
    technologies: ["Various engines", "QA tools", "Localization platforms", "Art pipelines"],
    culture: {
      workStyle: "remote-friendly",
      benefits: ["Global opportunities", "Health benefits", "Training programs"],
      diversity: "Diverse global workforce across multiple studios",
    },
    interviewStyle: "Skills-based assessment depending on role and service line",
    remoteWork: true,
  },
  {
    id: "microsoft-gaming",
    name: "Microsoft Gaming",
    logo: null,
    website: "https://www.xbox.com",
    location: "Redmond, WA",
    size: "1000+",
    type: "AAA",
    description:
      "Xbox parent company overseeing Halo, Minecraft, Bethesda, and Activision Blizzard studios.",
    games: ["Halo Infinite", "Minecraft", "Forza", "Gears of War", "Starfield", "Call of Duty"],
    technologies: ["Unreal Engine", "Proprietary engines", "Azure", "C++", "C#"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "Stock options", "Health coverage", "Career growth"],
      diversity: "Strong diversity and inclusion programs across gaming division",
    },
    interviewStyle: "Microsoft interview process with gaming-specific assessments",
    remoteWork: true,
  },
  {
    id: "asobo-studio",
    name: "Asobo Studio",
    logo: null,
    website: "https://www.asobostudio.com",
    location: "Bordeaux, France",
    size: "200-999",
    type: "Mid-size",
    description: "French studio behind A Plague Tale series and Microsoft Flight Simulator.",
    games: ["A Plague Tale: Innocence", "A Plague Tale: Requiem", "Microsoft Flight Simulator"],
    technologies: ["Proprietary Engine", "C++", "Photogrammetry", "Azure"],
    culture: {
      workStyle: "hybrid",
      benefits: ["French employment benefits", "Health coverage", "Creative environment"],
      diversity: "Growing French studio with international reach",
    },
    interviewStyle: "Technical assessment and portfolio review with focus on visual quality",
    remoteWork: true,
  },
  {
    id: "arrowhead-game-studios",
    name: "Arrowhead Game Studios",
    logo: null,
    website: "https://arrowheadgamestudios.com",
    location: "Stockholm, Sweden",
    size: "200-999",
    type: "Mid-size",
    description: "Swedish studio behind Helldivers 2 and cooperative action games.",
    games: ["Helldivers 2", "Helldivers", "Magicka"],
    technologies: ["Autodesk Stingray", "C++", "Proprietary tools"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Swedish benefits", "Health coverage", "Creative freedom"],
      diversity: "Independent spirit with focus on co-op gameplay",
    },
    interviewStyle: "Technical skills and passion for cooperative gameplay",
    remoteWork: true,
  },
  {
    id: "red-hook-studios",
    name: "Red Hook Studios",
    logo: null,
    website: "https://www.redhookgames.com",
    location: "Vancouver, Canada",
    size: "50-199",
    type: "Indie",
    description: "Independent studio known for Darkest Dungeon and its gothic art style.",
    games: ["Darkest Dungeon", "Darkest Dungeon II"],
    technologies: ["Unity Engine", "C#", "Custom art pipeline"],
    culture: {
      workStyle: "remote-friendly",
      benefits: ["Indie studio flexibility", "Health benefits", "Creative environment"],
      diversity: "Small team with strong creative vision",
    },
    interviewStyle: "Portfolio review and cultural fit for small team dynamics",
    remoteWork: true,
  },
  {
    id: "behaviour-interactive",
    name: "Behaviour Interactive",
    logo: null,
    website: "https://www.bhvr.com",
    location: "Montreal, Canada",
    size: "200-999",
    type: "Mid-size",
    description: "Canadian studio behind Dead by Daylight and co-development services.",
    games: ["Dead by Daylight", "Meet Your Maker", "Game of Thrones: Beyond the Wall"],
    technologies: ["Unreal Engine", "C++", "Live service infrastructure"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Canadian benefits", "Health coverage", "Game library"],
      diversity: "Growing studio with live service expertise",
    },
    interviewStyle: "Technical assessment with focus on live service experience",
    remoteWork: true,
  },
  {
    id: "virtuos",
    name: "Virtuos",
    logo: null,
    website: "https://www.virtuosgames.com",
    location: "Singapore",
    size: "500+",
    type: "Services",
    description: "Leading co-development and porting studio serving major publishers worldwide.",
    games: ["Porting services", "Co-development", "Art services", "AAA support"],
    technologies: ["Unreal Engine", "Unity", "Various proprietary engines", "Porting tools"],
    culture: {
      workStyle: "on-site",
      benefits: ["Regional benefits", "International opportunities", "Training programs"],
      diversity: "Global presence with studios across Asia and Europe",
    },
    interviewStyle: "Technical skills assessment and portfolio review",
    remoteWork: false,
  },
  {
    id: "visual-concepts",
    name: "Visual Concepts",
    logo: null,
    website: "https://www.vcentertainment.com",
    location: "Novato, CA",
    size: "1000+",
    type: "AAA",
    description: "2K studio specializing in sports games, particularly the NBA 2K series.",
    games: ["NBA 2K series", "WWE 2K series", "Lego 2K Drive"],
    technologies: ["Proprietary Engine", "C++", "Motion capture", "Sports simulation tech"],
    culture: {
      workStyle: "hybrid",
      benefits: ["2K benefits", "Health coverage", "Game discounts"],
      diversity: "Sports gaming focused culture",
    },
    interviewStyle: "Technical assessment with sports game development focus",
    remoteWork: true,
  },
  {
    id: "firaxis-games",
    name: "Firaxis Games",
    logo: null,
    website: "https://firaxis.com",
    location: "Sparks, MD",
    size: "200-999",
    type: "Mid-size",
    description: "2K studio famous for strategy games like Civilization and XCOM.",
    games: ["Civilization VI", "XCOM 2", "Marvel's Midnight Suns", "Civilization VII"],
    technologies: ["Unreal Engine", "Proprietary strategy tools", "C++"],
    culture: {
      workStyle: "hybrid",
      benefits: ["2K benefits", "Health coverage", "Strategy game culture"],
      diversity: "Strategy-focused development environment",
    },
    interviewStyle: "Strategy game knowledge and technical skills assessment",
    remoteWork: true,
  },
  {
    id: "gameloft",
    name: "Gameloft",
    logo: null,
    website: "https://www.gameloft.com",
    location: "Paris, France",
    size: "1000+",
    type: "Mobile",
    description: "Major mobile game publisher with studios worldwide.",
    games: ["Asphalt series", "Modern Combat", "Disney games", "Mobile ports"],
    technologies: ["Proprietary engines", "Unity", "Mobile SDKs", "C++"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Global opportunities", "Health benefits", "International mobility"],
      diversity: "Global workforce with studios on multiple continents",
    },
    interviewStyle: "Mobile development focus with portfolio review",
    remoteWork: true,
  },
  {
    id: "focus-entertainment",
    name: "Focus Entertainment",
    logo: null,
    website: "https://www.focus-entmt.com",
    location: "Paris, France",
    size: "200-999",
    type: "Mid-size",
    description: "French publisher and developer of AA games like A Plague Tale and GreedFall.",
    games: ["A Plague Tale publisher", "GreedFall", "Vampyr", "The Surge"],
    technologies: ["Various engines", "Publishing platform", "Development support"],
    culture: {
      workStyle: "hybrid",
      benefits: ["French benefits", "Health coverage", "Publisher-developer culture"],
      diversity: "Mid-tier publisher supporting creative projects",
    },
    interviewStyle: "Publishing and development role-specific interviews",
    remoteWork: true,
  },
  {
    id: "quantic-dream",
    name: "Quantic Dream",
    logo: null,
    website: "https://www.quanticdream.com",
    location: "Paris, France",
    size: "200-999",
    type: "Mid-size",
    description: "French studio known for interactive drama games with branching narratives.",
    games: ["Detroit: Become Human", "Heavy Rain", "Beyond: Two Souls"],
    technologies: ["Proprietary Engine", "Motion capture", "C++", "Narrative tools"],
    culture: {
      workStyle: "on-site",
      benefits: ["French benefits", "Creative environment", "Film industry connections"],
      diversity: "Cinematic game development focus",
    },
    interviewStyle: "Narrative and cinematic experience assessment",
    remoteWork: false,
  },
  {
    id: "team17",
    name: "Team17",
    logo: null,
    website: "https://www.team17.com",
    location: "Wakefield, UK",
    size: "200-999",
    type: "Mid-size",
    description: "British indie publisher and developer, famous for Worms franchise.",
    games: ["Worms series", "Overcooked publisher", "The Escapists", "Hell Let Loose"],
    technologies: ["Various engines", "Publishing platform", "Unity", "Unreal Engine"],
    culture: {
      workStyle: "hybrid",
      benefits: ["UK benefits", "Health coverage", "Indie culture"],
      diversity: "Indie-focused publisher with developer support",
    },
    interviewStyle: "Portfolio review and passion for indie games",
    remoteWork: true,
  },
  {
    id: "bloober-team",
    name: "Bloober Team",
    logo: null,
    website: "https://www.blooberteam.com",
    location: "Krakow, Poland",
    size: "200-999",
    type: "Mid-size",
    description: "Polish studio specializing in psychological horror games.",
    games: ["Layers of Fear", "The Medium", "Blair Witch", "Silent Hill 2 Remake"],
    technologies: ["Unreal Engine", "C++", "Horror-specific tools"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Polish benefits", "Health coverage", "Horror game expertise"],
      diversity: "Horror genre specialists",
    },
    interviewStyle: "Portfolio review with focus on horror and atmosphere",
    remoteWork: true,
  },
  {
    id: "people-can-fly",
    name: "People Can Fly",
    logo: null,
    website: "https://www.peoplecanfly.com",
    location: "Warsaw, Poland",
    size: "200-999",
    type: "Mid-size",
    description: "Polish action game developer behind Outriders and Bulletstorm.",
    games: ["Outriders", "Bulletstorm", "Gears of War: Judgment"],
    technologies: ["Unreal Engine", "C++", "Action game mechanics"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Polish benefits", "Health coverage", "International projects"],
      diversity: "Action-focused development culture",
    },
    interviewStyle: "Technical skills with focus on action gameplay",
    remoteWork: true,
  },
  {
    id: "coffee-stain-studios",
    name: "Coffee Stain Studios",
    logo: null,
    website: "https://www.coffeestainstudios.com",
    location: "Skövde, Sweden",
    size: "50-199",
    type: "Indie",
    description:
      "Swedish indie developer and publisher behind Satisfactory and Deep Rock Galactic.",
    games: ["Satisfactory", "Deep Rock Galactic publisher", "Goat Simulator"],
    technologies: ["Unreal Engine", "C++", "Proprietary tools"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Swedish benefits", "Creative freedom", "Indie culture"],
      diversity: "Independent and experimental game development",
    },
    interviewStyle: "Cultural fit and passion for unique game concepts",
    remoteWork: true,
  },
  {
    id: "playdead",
    name: "Playdead",
    logo: null,
    website: "https://playdead.com",
    location: "Copenhagen, Denmark",
    size: "50-199",
    type: "Indie",
    description: "Danish indie studio known for minimalist, atmospheric puzzle-platformers.",
    games: ["Inside", "Limbo"],
    technologies: ["Proprietary Engine", "C++", "Custom art tools"],
    culture: {
      workStyle: "on-site",
      benefits: ["Danish benefits", "Creative environment", "Art-focused culture"],
      diversity: "Small team with strong artistic vision",
    },
    interviewStyle: "Artistic and technical excellence assessment",
    remoteWork: false,
  },
  {
    id: "inworld-ai",
    name: "Inworld AI",
    logo: null,
    website: "https://www.inworld.ai",
    location: "Mountain View, CA",
    size: "50-199",
    type: "AI/Tech",
    description:
      "AI company creating intelligent NPCs and characters for games using generative AI.",
    games: ["AI NPC platform", "Character engine", "Conversational AI"],
    technologies: ["Machine Learning", "LLMs", "Unity SDK", "Unreal SDK", "Python", "Cloud"],
    culture: {
      workStyle: "remote-friendly",
      benefits: ["Startup equity", "Health benefits", "Cutting-edge AI work"],
      diversity: "Tech startup culture focused on AI innovation",
    },
    interviewStyle: "AI/ML technical assessment and gaming industry knowledge",
    remoteWork: true,
  },
  {
    id: "mainframe-industries",
    name: "Mainframe Industries",
    logo: null,
    website: "https://mainframeind.com",
    location: "Reykjavik, Iceland / Helsinki, Finland",
    size: "200-999",
    type: "Mid-size",
    description: "Cloud-native MMO developer working on next-generation multiplayer experiences.",
    games: ["Pax Dei", "Cloud-native MMO"],
    technologies: ["Cloud infrastructure", "C++", "Distributed systems", "AWS"],
    culture: {
      workStyle: "remote-friendly",
      benefits: ["Startup equity", "Health benefits", "Remote work", "Nordic benefits"],
      diversity: "Modern cloud-first development culture",
    },
    interviewStyle: "Cloud architecture and MMO experience assessment",
    remoteWork: true,
  },
  {
    id: "santa-monica-studio",
    name: "Santa Monica Studio",
    logo: null,
    website: "https://sms.playstation.com",
    location: "Los Angeles, CA",
    size: "1000+",
    type: "AAA",
    description: "Sony studio behind the God of War franchise.",
    games: ["God of War (2018)", "God of War Ragnarök", "God of War series"],
    technologies: ["Proprietary Engine", "C++", "PlayStation SDKs", "Motion capture"],
    culture: {
      workStyle: "hybrid",
      benefits: ["PlayStation benefits", "Health coverage", "Creative environment"],
      diversity: "Focus on mature storytelling and technical excellence",
    },
    interviewStyle: "Technical excellence and portfolio review",
    remoteWork: true,
  },
  {
    id: "guerrilla-games",
    name: "Guerrilla Games",
    logo: null,
    website: "https://www.guerrilla-games.com",
    location: "Amsterdam, Netherlands",
    size: "1000+",
    type: "AAA",
    description: "Sony studio known for Horizon series and Decima engine.",
    games: ["Horizon Zero Dawn", "Horizon Forbidden West", "Killzone series"],
    technologies: ["Decima Engine", "C++", "Python", "PlayStation SDKs"],
    culture: {
      workStyle: "hybrid",
      benefits: ["PlayStation benefits", "Dutch benefits", "International environment"],
      diversity: "Dutch studio with international team",
    },
    interviewStyle: "Technical assessment and engine development focus",
    remoteWork: true,
  },
  {
    id: "square-enix",
    name: "Square Enix",
    logo: null,
    website: "https://www.square-enix.com",
    location: "Tokyo, Japan",
    size: "1000+",
    type: "AAA",
    description:
      "Major Japanese publisher and developer of Final Fantasy, Dragon Quest, and Kingdom Hearts.",
    games: ["Final Fantasy series", "Dragon Quest", "Kingdom Hearts", "NieR"],
    technologies: ["Luminous Engine", "Unreal Engine", "C++", "Proprietary tools"],
    culture: {
      workStyle: "on-site",
      benefits: ["Japanese benefits", "Health coverage", "JRPG culture"],
      diversity: "Traditional Japanese game development with global reach",
    },
    interviewStyle: "Technical skills and JRPG development experience",
    remoteWork: false,
  },
  {
    id: "capcom",
    name: "Capcom",
    logo: null,
    website: "https://www.capcom.com",
    location: "Osaka, Japan",
    size: "1000+",
    type: "AAA",
    description:
      "Legendary Japanese developer of Resident Evil, Monster Hunter, and Street Fighter.",
    games: ["Resident Evil series", "Monster Hunter", "Street Fighter", "Devil May Cry"],
    technologies: ["RE Engine", "MT Framework", "C++", "Proprietary tools"],
    culture: {
      workStyle: "on-site",
      benefits: ["Japanese benefits", "Health coverage", "Legacy franchises"],
      diversity: "Long-standing Japanese game development traditions",
    },
    interviewStyle: "Technical excellence and franchise knowledge assessment",
    remoteWork: false,
  },
  {
    id: "nintendo-epd",
    name: "Nintendo EPD",
    logo: null,
    website: "https://www.nintendo.com",
    location: "Kyoto, Japan",
    size: "1000+",
    type: "AAA",
    description:
      "Nintendo's internal development division creating Mario, Zelda, and Pokemon games.",
    games: ["Super Mario series", "The Legend of Zelda", "Animal Crossing", "Splatoon"],
    technologies: ["Proprietary engines", "C++", "Nintendo hardware SDKs"],
    culture: {
      workStyle: "on-site",
      benefits: ["Japanese benefits", "Nintendo culture", "Family-friendly focus"],
      diversity: "Traditional Nintendo development philosophy",
    },
    interviewStyle: "Extremely selective with focus on Nintendo game design philosophy",
    remoteWork: false,
  },
  {
    id: "bandai-namco",
    name: "Bandai Namco",
    logo: null,
    website: "https://www.bandainamcoent.com",
    location: "Tokyo, Japan",
    size: "1000+",
    type: "AAA",
    description: "Major Japanese publisher behind Tekken, Tales, and publisher of Elden Ring.",
    games: ["Tekken", "Tales series", "Elden Ring publisher", "Pac-Man", "Dragon Ball games"],
    technologies: ["Unreal Engine", "Proprietary engines", "C++"],
    culture: {
      workStyle: "on-site",
      benefits: ["Japanese benefits", "Health coverage", "Anime/gaming crossover"],
      diversity: "Japanese publisher with global franchises",
    },
    interviewStyle: "Technical skills and franchise knowledge",
    remoteWork: false,
  },
  {
    id: "sega",
    name: "SEGA",
    logo: null,
    website: "https://www.sega.com",
    location: "Tokyo, Japan",
    size: "1000+",
    type: "AAA",
    description: "Historic Japanese publisher behind Sonic, Yakuza, and Total War franchises.",
    games: ["Sonic series", "Yakuza/Like a Dragon", "Total War", "Persona", "Phantasy Star Online"],
    technologies: ["Various engines", "Hedgehog Engine", "C++", "Unreal Engine"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Japanese benefits", "Health coverage", "Diverse portfolio"],
      diversity: "Mix of Japanese and Western development studios",
    },
    interviewStyle: "Role-specific with focus on franchise experience",
    remoteWork: true,
  },
  {
    id: "bethesda-game-studios",
    name: "Bethesda Game Studios",
    logo: null,
    website: "https://bethesdagamestudios.com",
    location: "Rockville, MD",
    size: "1000+",
    type: "AAA",
    description: "Microsoft studio behind Elder Scrolls, Fallout, and Starfield.",
    games: ["Starfield", "The Elder Scrolls series", "Fallout series"],
    technologies: ["Creation Engine", "C++", "Proprietary tools"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "Health coverage", "Open-world RPG culture"],
      diversity: "Focus on player-driven open worlds",
    },
    interviewStyle: "RPG development experience and technical skills",
    remoteWork: true,
  },
  {
    id: "id-software",
    name: "id Software",
    logo: null,
    website: "https://www.idsoftware.com",
    location: "Dallas, TX",
    size: "1000+",
    type: "AAA",
    description: "Legendary FPS developer behind DOOM, Quake, and pioneers of 3D gaming.",
    games: ["DOOM Eternal", "DOOM (2016)", "Quake", "Wolfenstein"],
    technologies: ["id Tech engine", "C++", "Vulkan", "Advanced graphics"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "Health coverage", "FPS expertise"],
      diversity: "Historic studio with cutting-edge graphics focus",
    },
    interviewStyle: "Graphics programming and FPS development expertise",
    remoteWork: true,
  },
  {
    id: "machine-games",
    name: "Machine Games",
    logo: null,
    website: "https://www.machinegames.com",
    location: "Uppsala, Sweden",
    size: "1000+",
    type: "AAA",
    description: "Microsoft studio developing Wolfenstein and Indiana Jones games.",
    games: ["Wolfenstein: The New Order", "Wolfenstein II", "Indiana Jones game"],
    technologies: ["id Tech engine", "C++", "Narrative tools"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "Swedish benefits", "Narrative FPS focus"],
      diversity: "Swedish studio with story-driven FPS expertise",
    },
    interviewStyle: "FPS and narrative experience assessment",
    remoteWork: true,
  },
  {
    id: "playground-games",
    name: "Playground Games",
    logo: null,
    website: "https://www.playground-games.com",
    location: "Leamington Spa, UK",
    size: "1000+",
    type: "AAA",
    description: "Microsoft studio behind Forza Horizon and developing Fable reboot.",
    games: ["Forza Horizon series", "Fable (upcoming)"],
    technologies: ["ForzaTech engine", "Unreal Engine", "C++", "Racing simulation"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "UK benefits", "Racing game culture"],
      diversity: "UK studio with racing and RPG development",
    },
    interviewStyle: "Technical skills with racing or open-world experience",
    remoteWork: true,
  },
  {
    id: "turn-10-studios",
    name: "Turn 10 Studios",
    logo: null,
    website: "https://www.turn10studios.com",
    location: "Redmond, WA",
    size: "1000+",
    type: "AAA",
    description: "Microsoft studio specializing in Forza Motorsport simulation racing.",
    games: ["Forza Motorsport series"],
    technologies: ["ForzaTech engine", "C++", "Racing simulation", "Physics engines"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "Health coverage", "Simulation focus"],
      diversity: "Technical racing simulation expertise",
    },
    interviewStyle: "Physics and simulation programming assessment",
    remoteWork: true,
  },
  {
    id: "halo-studios",
    name: "343 Industries/Halo Studios",
    logo: null,
    website: "https://www.halowaypoint.com",
    location: "Redmond, WA",
    size: "1000+",
    type: "AAA",
    description:
      "Microsoft studio dedicated to the Halo franchise, recently rebranded to Halo Studios.",
    games: ["Halo Infinite", "Halo 5: Guardians", "Halo: The Master Chief Collection"],
    technologies: ["Slipspace Engine", "Unreal Engine 5", "C++", "Live service"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "Health coverage", "Halo franchise culture"],
      diversity: "Focus on maintaining Halo legacy and innovation",
    },
    interviewStyle: "FPS experience and Halo franchise knowledge",
    remoteWork: true,
  },
  {
    id: "double-fine",
    name: "Double Fine",
    logo: null,
    website: "https://www.doublefine.com",
    location: "San Francisco, CA",
    size: "200-999",
    type: "Mid-size",
    description: "Microsoft studio known for creative, quirky games like Psychonauts.",
    games: ["Psychonauts 2", "Brutal Legend", "Grim Fandango", "Broken Age"],
    technologies: ["Unreal Engine", "Proprietary tools", "C++"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "Creative environment", "Unique game design"],
      diversity: "Indie spirit with AAA backing",
    },
    interviewStyle: "Creative portfolio and cultural fit assessment",
    remoteWork: true,
  },
  {
    id: "devolver-digital",
    name: "Devolver Digital",
    logo: null,
    website: "https://www.devolverdigital.com",
    location: "Austin, TX",
    size: "500+",
    type: "Publisher",
    description: "Independent publisher known for unique indie games and irreverent marketing.",
    games: ["Hotline Miami", "Cult of the Lamb", "Death's Door", "Enter the Gungeon"],
    technologies: ["Various indie engines", "Publishing platform"],
    culture: {
      workStyle: "remote-friendly",
      benefits: ["Publisher benefits", "Creative freedom", "Indie culture"],
      diversity: "Support for unique and experimental games",
    },
    interviewStyle: "Passion for indie games and publishing experience",
    remoteWork: true,
  },
  {
    id: "annapurna-interactive",
    name: "Annapurna Interactive",
    logo: null,
    website: "https://annapurnainteractive.com",
    location: "Los Angeles, CA",
    size: "500+",
    type: "Publisher",
    description:
      "Premium indie publisher behind critically acclaimed narrative and artistic games.",
    games: ["Stray", "Outer Wilds", "What Remains of Edith Finch", "Kentucky Route Zero"],
    technologies: ["Various indie engines", "Publishing support"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Publisher benefits", "Film industry connections", "Artistic focus"],
      diversity: "Focus on artistic and narrative excellence",
    },
    interviewStyle: "Appreciation for artistic games and publishing expertise",
    remoteWork: true,
  },
  {
    id: "thatgamecompany",
    name: "thatgamecompany",
    logo: null,
    website: "https://thatgamecompany.com",
    location: "Santa Monica, CA",
    size: "50-199",
    type: "Indie",
    description:
      "Independent studio creating emotionally resonant experiences like Journey and Sky.",
    games: ["Sky: Children of the Light", "Journey", "Flower", "Flow"],
    technologies: ["Proprietary Engine", "C++", "Mobile optimization"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Creative environment", "Health benefits", "Artistic focus"],
      diversity: "Focus on emotional and artistic game experiences",
    },
    interviewStyle: "Artistic vision and technical skills assessment",
    remoteWork: true,
  },
  {
    id: "supergiant-games",
    name: "Supergiant Games",
    logo: null,
    website: "https://www.supergiantgames.com",
    location: "San Francisco, CA",
    size: "50-199",
    type: "Indie",
    description: "Acclaimed indie studio behind Hades, Bastion, and Transistor.",
    games: ["Hades", "Hades II", "Transistor", "Bastion", "Pyre"],
    technologies: ["Proprietary Engine", "C++", "Custom tools"],
    culture: {
      workStyle: "remote-friendly",
      benefits: ["Indie benefits", "Creative freedom", "Small team culture"],
      diversity: "Small independent team with strong creative vision",
    },
    interviewStyle: "Portfolio review and passion for indie game development",
    remoteWork: true,
  },
  {
    id: "ninja-theory",
    name: "Ninja Theory",
    logo: null,
    website: "https://www.ninjatheory.com",
    location: "Cambridge, UK",
    size: "1000+",
    type: "AAA",
    description: "Microsoft studio known for Hellblade and narrative-driven action games.",
    games: ["Hellblade: Senua's Sacrifice", "Hellblade II: Senua's Saga", "DmC: Devil May Cry"],
    technologies: ["Unreal Engine", "Motion capture", "Audio innovation", "C++"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "UK benefits", "Mental health focus"],
      diversity: "Focus on mental health themes and authentic representation",
    },
    interviewStyle: "Narrative and technical excellence assessment",
    remoteWork: true,
  },
  {
    id: "rare",
    name: "Rare",
    logo: null,
    website: "https://www.rare.co.uk",
    location: "Twycross, UK",
    size: "1000+",
    type: "AAA",
    description: "Historic Microsoft studio behind Sea of Thieves, GoldenEye, and Banjo-Kazooie.",
    games: ["Sea of Thieves", "Everwild", "Perfect Dark", "Banjo-Kazooie legacy"],
    technologies: ["Proprietary Engine", "Unreal Engine", "C++", "Live service"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Microsoft benefits", "UK benefits", "Historic studio culture"],
      diversity: "Legacy studio with modern live service focus",
    },
    interviewStyle: "Live service experience and British gaming heritage",
    remoteWork: true,
  },
  {
    id: "crystal-dynamics",
    name: "Crystal Dynamics",
    logo: null,
    website: "https://crystald.com",
    location: "San Mateo, CA",
    size: "1000+",
    type: "AAA",
    description: "Embracer studio known for Tomb Raider series and action-adventure games.",
    games: [
      "Tomb Raider (2013)",
      "Rise of the Tomb Raider",
      "Shadow of the Tomb Raider",
      "Legacy of Kain",
    ],
    technologies: ["Unreal Engine", "Proprietary Foundation engine", "C++"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Health benefits", "Game discounts", "Action-adventure focus"],
      diversity: "Focus on strong female protagonists and cinematic experiences",
    },
    interviewStyle: "Action-adventure experience and technical skills",
    remoteWork: true,
  },
  {
    id: "eidos-montreal",
    name: "Eidos Montreal",
    logo: null,
    website: "https://www.eidosmontreal.com",
    location: "Montreal, Canada",
    size: "1000+",
    type: "AAA",
    description: "Embracer studio behind Deus Ex and Guardians of the Galaxy games.",
    games: [
      "Deus Ex: Human Revolution",
      "Deus Ex: Mankind Divided",
      "Marvel's Guardians of the Galaxy",
    ],
    technologies: ["Dawn Engine", "Unreal Engine", "C++"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Canadian benefits", "Health coverage", "Montreal gaming hub"],
      diversity: "Immersive sim and narrative-driven game focus",
    },
    interviewStyle: "Immersive sim experience and technical assessment",
    remoteWork: true,
  },
  {
    id: "io-interactive",
    name: "IO Interactive",
    logo: null,
    website: "https://www.ioi.dk",
    location: "Copenhagen, Denmark",
    size: "200-999",
    type: "Mid-size",
    description: "Independent studio behind Hitman trilogy and developing James Bond game.",
    games: ["Hitman trilogy", "James Bond Project 007", "Kane & Lynch legacy"],
    technologies: ["Glacier Engine", "C++", "Proprietary tools"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Danish benefits", "Health coverage", "Creative independence"],
      diversity: "Independent with focus on player freedom and systemic gameplay",
    },
    interviewStyle: "Systemic design knowledge and technical skills",
    remoteWork: true,
  },
  {
    id: "techland",
    name: "Techland",
    logo: null,
    website: "https://www.techland.pl",
    location: "Wroclaw, Poland",
    size: "200-999",
    type: "Mid-size",
    description: "Polish studio behind Dying Light franchise and open-world zombie games.",
    games: ["Dying Light 2: Stay Human", "Dying Light", "Dead Island"],
    technologies: ["C-Engine", "C++", "Open-world tools"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Polish benefits", "Health coverage", "Open-world focus"],
      diversity: "Focus on parkour and zombie survival",
    },
    interviewStyle: "Open-world and melee combat system experience",
    remoteWork: true,
  },
  {
    id: "4a-games",
    name: "4A Games",
    logo: null,
    website: "https://www.4a-games.com",
    location: "Kyiv, Ukraine",
    size: "200-999",
    type: "Mid-size",
    description: "Ukrainian studio known for Metro series and atmospheric survival shooters.",
    games: ["Metro Exodus", "Metro: Last Light", "Metro 2033"],
    technologies: ["4A Engine", "C++", "Advanced rendering"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Regional benefits", "Creative environment", "Technical excellence"],
      diversity: "Focus on atmospheric and immersive experiences",
    },
    interviewStyle: "Graphics programming and atmospheric game design",
    remoteWork: true,
  },
  {
    id: "wargaming",
    name: "Wargaming",
    logo: null,
    website: "https://wargaming.com",
    location: "Nicosia, Cyprus",
    size: "200-999",
    type: "Mid-size",
    description: "Developer and publisher of World of Tanks and military vehicle games.",
    games: ["World of Tanks", "World of Warships", "World of Warplanes"],
    technologies: ["BigWorld Engine", "C++", "Live service infrastructure"],
    culture: {
      workStyle: "hybrid",
      benefits: ["International benefits", "Health coverage", "Military simulation focus"],
      diversity: "Global offices with military vehicle focus",
    },
    interviewStyle: "Live service and simulation experience",
    remoteWork: true,
  },
  {
    id: "digital-extremes",
    name: "Digital Extremes",
    logo: null,
    website: "https://www.digitalextremes.com",
    location: "London, Ontario, Canada",
    size: "200-999",
    type: "Mid-size",
    description: "Canadian studio behind free-to-play live service game Warframe.",
    games: ["Warframe", "The Darkness II", "Unreal Tournament legacy"],
    technologies: ["Evolution Engine", "C++", "Live service infrastructure"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Canadian benefits", "Health coverage", "Community-driven development"],
      diversity: "Strong community focus and live service expertise",
    },
    interviewStyle: "Live service and F2P experience assessment",
    remoteWork: true,
  },
  {
    id: "grinding-gear-games",
    name: "Grinding Gear Games",
    logo: null,
    website: "https://www.grindinggear.com",
    location: "Auckland, New Zealand",
    size: "200-999",
    type: "Mid-size",
    description: "New Zealand studio behind Path of Exile ARPG franchise.",
    games: ["Path of Exile", "Path of Exile 2"],
    technologies: ["Proprietary Engine", "C++", "Live service infrastructure"],
    culture: {
      workStyle: "hybrid",
      benefits: ["NZ benefits", "Health coverage", "ARPG expertise"],
      diversity: "Focus on deep ARPG mechanics and live seasons",
    },
    interviewStyle: "ARPG knowledge and systems design experience",
    remoteWork: true,
  },
  {
    id: "massive-entertainment",
    name: "Massive Entertainment",
    logo: null,
    website: "https://www.massive.se",
    location: "Malmö, Sweden",
    size: "1000+",
    type: "AAA",
    description: "Ubisoft studio behind The Division and Star Wars Outlaws.",
    games: ["The Division 2", "Star Wars Outlaws", "The Division", "Ground Control legacy"],
    technologies: ["Snowdrop Engine", "C++", "Live service tools"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Ubisoft benefits", "Swedish benefits", "Open-world focus"],
      diversity: "Swedish studio with AAA open-world expertise",
    },
    interviewStyle: "Open-world and live service experience",
    remoteWork: true,
  },
  {
    id: "netease-games",
    name: "NetEase Games",
    logo: null,
    website: "https://www.neteasegames.com",
    location: "Guangzhou, China",
    size: "1000+",
    type: "AAA",
    description: "Major Chinese gaming company developing mobile and PC games.",
    games: ["Marvel Rivals", "Naraka: Bladepoint", "Identity V", "Eggy Party"],
    technologies: ["Unreal Engine", "Unity", "Proprietary engines", "C++"],
    culture: {
      workStyle: "on-site",
      benefits: ["Chinese benefits", "Health coverage", "Competitive compensation"],
      diversity: "Major Chinese developer with global ambitions",
    },
    interviewStyle: "Technical skills and mobile/live service experience",
    remoteWork: false,
  },
  {
    id: "tencent-games",
    name: "Tencent Games",
    logo: null,
    website: "https://game.qq.com",
    location: "Shenzhen, China",
    size: "1000+",
    type: "AAA",
    description:
      "World's largest gaming company by revenue, owning Riot, Epic stake, and major publishers.",
    games: ["Honor of Kings", "PUBG Mobile", "League of Legends owner", "Riot Games owner"],
    technologies: ["Various engines", "Mobile SDKs", "C++", "Cloud infrastructure"],
    culture: {
      workStyle: "on-site",
      benefits: ["Chinese benefits", "Competitive compensation", "Global reach"],
      diversity: "Massive conglomerate with investments across gaming industry",
    },
    interviewStyle: "Role-specific with focus on scale and mobile experience",
    remoteWork: false,
  },
  {
    id: "ccp-games",
    name: "CCP Games",
    logo: null,
    website: "https://www.ccpgames.com",
    location: "Reykjavik, Iceland",
    size: "200-999",
    type: "Mid-size",
    description: "Icelandic studio behind EVE Online MMO and sci-fi gaming universe.",
    games: ["EVE Online", "EVE Echoes"],
    technologies: ["Proprietary Engine", "C++", "Python", "MMO infrastructure"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Icelandic benefits", "Health coverage", "MMO expertise"],
      diversity: "Focus on player-driven economy and complex systems",
    },
    interviewStyle: "MMO and systems design experience",
    remoteWork: true,
  },
  {
    id: "paradox-interactive",
    name: "Paradox Interactive",
    logo: null,
    website: "https://www.paradoxinteractive.com",
    location: "Stockholm, Sweden",
    size: "200-999",
    type: "Mid-size",
    description: "Swedish publisher and developer of grand strategy games.",
    games: ["Crusader Kings III", "Europa Universalis IV", "Stellaris", "Hearts of Iron IV"],
    technologies: ["Clausewitz Engine", "Jomini Engine", "C++", "Strategy tools"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Swedish benefits", "Health coverage", "Strategy game focus"],
      diversity: "Deep strategy game expertise with modding support",
    },
    interviewStyle: "Strategy game knowledge and systems design",
    remoteWork: true,
  },
  {
    id: "moon-studios",
    name: "Moon Studios",
    logo: null,
    website: "https://www.oriblindforest.com",
    location: "Vienna, Austria",
    size: "50-199",
    type: "Indie",
    description: "Indie studio behind Ori series, known for beautiful Metroidvania games.",
    games: ["Ori and the Blind Forest", "Ori and the Will of the Wisps"],
    technologies: ["Unity Engine", "C#", "Custom art pipeline"],
    culture: {
      workStyle: "remote-friendly",
      benefits: ["Remote-first", "Creative environment", "Visual excellence"],
      diversity: "Fully remote studio with international team",
    },
    interviewStyle: "Artistic and technical excellence assessment",
    remoteWork: true,
  },
  {
    id: "ember-lab",
    name: "Ember Lab",
    logo: null,
    website: "https://www.emberlab.com",
    location: "Carlsbad, CA",
    size: "50-199",
    type: "Indie",
    description: "Animation studio turned game developer, creators of Kena: Bridge of Spirits.",
    games: ["Kena: Bridge of Spirits"],
    technologies: ["Unreal Engine", "C++", "Animation pipeline"],
    culture: {
      workStyle: "hybrid",
      benefits: ["Animation studio benefits", "Creative environment", "Cinematic focus"],
      diversity: "Animation background with film-quality visuals",
    },
    interviewStyle: "Animation and visual design expertise",
    remoteWork: true,
  },
];
