/**
 * Extra layout SSOT surface (badges / ghost / inset).
 * Values are imported then re-exported so this module is not a pure barrel.
 */

import {
  ACCENT_ACTION_CLASS as _ACCENT_ACTION_CLASS,
  SECONDARY_ACTION_CLASS as _SECONDARY_ACTION_CLASS,
  SECONDARY_ACTION_DENSE_CLASS as _SECONDARY_ACTION_DENSE_CLASS,
} from "./layout-action-soft";
import {
  BADGE_ACCENT_CLASS as _BADGE_ACCENT_CLASS,
  BADGE_ACCENT_LG_CLASS as _BADGE_ACCENT_LG_CLASS,
  BADGE_ACCENT_SM_CLASS as _BADGE_ACCENT_SM_CLASS,
  BADGE_ERROR_CLASS as _BADGE_ERROR_CLASS,
  BADGE_ERROR_SM_CLASS as _BADGE_ERROR_SM_CLASS,
  BADGE_GHOST_CLASS as _BADGE_GHOST_CLASS,
  BADGE_GHOST_SM_CLASS as _BADGE_GHOST_SM_CLASS,
  BADGE_GHOST_XS_CLASS as _BADGE_GHOST_XS_CLASS,
  BADGE_INFO_CLASS as _BADGE_INFO_CLASS,
  BADGE_INFO_OUTLINE_CLASS as _BADGE_INFO_OUTLINE_CLASS,
  BADGE_INFO_SM_CLASS as _BADGE_INFO_SM_CLASS,
  BADGE_LG_CLASS as _BADGE_LG_CLASS,
  BADGE_NEUTRAL_CLASS as _BADGE_NEUTRAL_CLASS,
  BADGE_NEUTRAL_SM_CLASS as _BADGE_NEUTRAL_SM_CLASS,
  BADGE_OUTLINE_CLASS as _BADGE_OUTLINE_CLASS,
  BADGE_OUTLINE_MUTED_CLASS as _BADGE_OUTLINE_MUTED_CLASS,
  BADGE_OUTLINE_SM_CLASS as _BADGE_OUTLINE_SM_CLASS,
  BADGE_OUTLINE_XS_CLASS as _BADGE_OUTLINE_XS_CLASS,
  BADGE_PRIMARY_CLASS as _BADGE_PRIMARY_CLASS,
  BADGE_PRIMARY_LG_CLASS as _BADGE_PRIMARY_LG_CLASS,
  BADGE_PRIMARY_OUTLINE_CLASS as _BADGE_PRIMARY_OUTLINE_CLASS,
  BADGE_PRIMARY_SM_CLASS as _BADGE_PRIMARY_SM_CLASS,
  BADGE_PRIMARY_XS_CLASS as _BADGE_PRIMARY_XS_CLASS,
  BADGE_SECONDARY_CLASS as _BADGE_SECONDARY_CLASS,
  BADGE_SECONDARY_OUTLINE_CLASS as _BADGE_SECONDARY_OUTLINE_CLASS,
  BADGE_SM_CLASS as _BADGE_SM_CLASS,
  BADGE_SOFT_ERROR_CLASS as _BADGE_SOFT_ERROR_CLASS,
  BADGE_SOFT_INFO_CLASS as _BADGE_SOFT_INFO_CLASS,
  BADGE_SOFT_INFO_XS_CLASS as _BADGE_SOFT_INFO_XS_CLASS,
  BADGE_SOFT_NEUTRAL_CLASS as _BADGE_SOFT_NEUTRAL_CLASS,
  BADGE_SOFT_PRIMARY_CLASS as _BADGE_SOFT_PRIMARY_CLASS,
  BADGE_SOFT_PRIMARY_XS_CLASS as _BADGE_SOFT_PRIMARY_XS_CLASS,
  BADGE_SOFT_SM_CLASS as _BADGE_SOFT_SM_CLASS,
  BADGE_SOFT_SUCCESS_CLASS as _BADGE_SOFT_SUCCESS_CLASS,
  BADGE_SOFT_WARNING_CLASS as _BADGE_SOFT_WARNING_CLASS,
  BADGE_SOFT_WARNING_SM_CLASS as _BADGE_SOFT_WARNING_SM_CLASS,
  BADGE_SUCCESS_CLASS as _BADGE_SUCCESS_CLASS,
  BADGE_SUCCESS_SM_CLASS as _BADGE_SUCCESS_SM_CLASS,
  BADGE_VARIANT_CLASS as _BADGE_VARIANT_CLASS,
  BADGE_WARNING_CLASS as _BADGE_WARNING_CLASS,
  BADGE_WARNING_SM_CLASS as _BADGE_WARNING_SM_CLASS,
  BADGE_WARNING_XS_CLASS as _BADGE_WARNING_XS_CLASS,
  BADGE_XS_CLASS as _BADGE_XS_CLASS,
  type BadgeVariant as _BadgeVariant,
} from "./layout-badges";
import {
  CARD_BODY_CLASS as _CARD_BODY_CLASS,
  CARD_BODY_COMPACT_CLASS as _CARD_BODY_COMPACT_CLASS,
  FIELDSET_PANEL_CLASS as _FIELDSET_PANEL_CLASS,
  INSET_LIST_CLASS as _INSET_LIST_CLASS,
  INSET_PANEL_CLASS as _INSET_PANEL_CLASS,
  INSET_PANEL_MUTED_CLASS as _INSET_PANEL_MUTED_CLASS,
} from "./layout-shell";
import {
  BTN_VARIANT_CLASS as _BTN_VARIANT_CLASS,
  type BtnVariant as _BtnVariant,
  ERROR_ACTION_CLASS as _ERROR_ACTION_CLASS,
  GHOST_ACTION_CIRCLE_DENSE_CLASS as _GHOST_ACTION_CIRCLE_DENSE_CLASS,
  GHOST_ACTION_CLASS as _GHOST_ACTION_CLASS,
  GHOST_ACTION_DENSE_CLASS as _GHOST_ACTION_DENSE_CLASS,
  GHOST_ACTION_ERROR_DENSE_CLASS as _GHOST_ACTION_ERROR_DENSE_CLASS,
  GHOST_ACTION_PRINT_HIDDEN_CLASS as _GHOST_ACTION_PRINT_HIDDEN_CLASS,
  GHOST_ACTION_SQUARE_CLASS as _GHOST_ACTION_SQUARE_CLASS,
  LINK_ACTION_CLASS as _LINK_ACTION_CLASS,
  LINK_ACTION_DENSE_CLASS as _LINK_ACTION_DENSE_CLASS,
  OUTLINE_ACTION_DENSE_CLASS as _OUTLINE_ACTION_DENSE_CLASS,
  OUTLINE_ACTION_ERROR_CLASS as _OUTLINE_ACTION_ERROR_CLASS,
  OUTLINE_ACTION_ERROR_DENSE_CLASS as _OUTLINE_ACTION_ERROR_DENSE_CLASS,
  OUTLINE_ACTION_JOIN_CLASS as _OUTLINE_ACTION_JOIN_CLASS,
  OUTLINE_ACTION_PRINT_HIDDEN_CLASS as _OUTLINE_ACTION_PRINT_HIDDEN_CLASS,
  OUTLINE_ACTION_SECONDARY_CLASS as _OUTLINE_ACTION_SECONDARY_CLASS,
  SUCCESS_ACTION_CLASS as _SUCCESS_ACTION_CLASS,
} from "./layout-tokens-actions";

export const ACCENT_ACTION_CLASS = _ACCENT_ACTION_CLASS;
export const SECONDARY_ACTION_CLASS = _SECONDARY_ACTION_CLASS;
export const SECONDARY_ACTION_DENSE_CLASS = _SECONDARY_ACTION_DENSE_CLASS;
export const BADGE_SOFT_INFO_CLASS = _BADGE_SOFT_INFO_CLASS;
export const BADGE_SOFT_PRIMARY_CLASS = _BADGE_SOFT_PRIMARY_CLASS;
export const BADGE_SOFT_INFO_XS_CLASS = _BADGE_SOFT_INFO_XS_CLASS;
export const BADGE_SOFT_PRIMARY_XS_CLASS = _BADGE_SOFT_PRIMARY_XS_CLASS;
export const BADGE_SOFT_SM_CLASS = _BADGE_SOFT_SM_CLASS;
export const BADGE_SOFT_WARNING_CLASS = _BADGE_SOFT_WARNING_CLASS;
export const BADGE_SOFT_WARNING_SM_CLASS = _BADGE_SOFT_WARNING_SM_CLASS;
export const BADGE_SOFT_NEUTRAL_CLASS = _BADGE_SOFT_NEUTRAL_CLASS;
export const BADGE_SOFT_SUCCESS_CLASS = _BADGE_SOFT_SUCCESS_CLASS;
export const BADGE_GHOST_CLASS = _BADGE_GHOST_CLASS;
export const BADGE_GHOST_SM_CLASS = _BADGE_GHOST_SM_CLASS;
export const BADGE_GHOST_XS_CLASS = _BADGE_GHOST_XS_CLASS;
export const BADGE_SUCCESS_SM_CLASS = _BADGE_SUCCESS_SM_CLASS;
export const BADGE_SUCCESS_CLASS = _BADGE_SUCCESS_CLASS;
export const BADGE_ERROR_SM_CLASS = _BADGE_ERROR_SM_CLASS;
export const BADGE_ERROR_CLASS = _BADGE_ERROR_CLASS;
export const BADGE_SOFT_ERROR_CLASS = _BADGE_SOFT_ERROR_CLASS;
export const BADGE_WARNING_SM_CLASS = _BADGE_WARNING_SM_CLASS;
export const BADGE_WARNING_CLASS = _BADGE_WARNING_CLASS;
export const BADGE_WARNING_XS_CLASS = _BADGE_WARNING_XS_CLASS;
export const BADGE_INFO_SM_CLASS = _BADGE_INFO_SM_CLASS;
export const BADGE_INFO_CLASS = _BADGE_INFO_CLASS;
export const BADGE_INFO_OUTLINE_CLASS = _BADGE_INFO_OUTLINE_CLASS;
export const BADGE_PRIMARY_SM_CLASS = _BADGE_PRIMARY_SM_CLASS;
export const BADGE_PRIMARY_CLASS = _BADGE_PRIMARY_CLASS;
export const BADGE_PRIMARY_OUTLINE_CLASS = _BADGE_PRIMARY_OUTLINE_CLASS;
export const BADGE_PRIMARY_LG_CLASS = _BADGE_PRIMARY_LG_CLASS;
export const BADGE_PRIMARY_XS_CLASS = _BADGE_PRIMARY_XS_CLASS;
export const BADGE_OUTLINE_SM_CLASS = _BADGE_OUTLINE_SM_CLASS;
export const BADGE_OUTLINE_CLASS = _BADGE_OUTLINE_CLASS;
export const BADGE_OUTLINE_XS_CLASS = _BADGE_OUTLINE_XS_CLASS;
export const BADGE_SM_CLASS = _BADGE_SM_CLASS;
export const BADGE_LG_CLASS = _BADGE_LG_CLASS;
export const BADGE_XS_CLASS = _BADGE_XS_CLASS;
export const BADGE_NEUTRAL_SM_CLASS = _BADGE_NEUTRAL_SM_CLASS;
export const BADGE_NEUTRAL_CLASS = _BADGE_NEUTRAL_CLASS;
export const BADGE_SECONDARY_CLASS = _BADGE_SECONDARY_CLASS;
export const BADGE_ACCENT_CLASS = _BADGE_ACCENT_CLASS;
export const BADGE_ACCENT_SM_CLASS = _BADGE_ACCENT_SM_CLASS;
export const BADGE_OUTLINE_MUTED_CLASS = _BADGE_OUTLINE_MUTED_CLASS;
export const BADGE_ACCENT_LG_CLASS = _BADGE_ACCENT_LG_CLASS;
export const BADGE_SECONDARY_OUTLINE_CLASS = _BADGE_SECONDARY_OUTLINE_CLASS;
export const BADGE_VARIANT_CLASS = _BADGE_VARIANT_CLASS;
export type BadgeVariant = _BadgeVariant;
export const CARD_BODY_CLASS = _CARD_BODY_CLASS;
export const CARD_BODY_COMPACT_CLASS = _CARD_BODY_COMPACT_CLASS;
export const FIELDSET_PANEL_CLASS = _FIELDSET_PANEL_CLASS;
export const INSET_LIST_CLASS = _INSET_LIST_CLASS;
export const INSET_PANEL_CLASS = _INSET_PANEL_CLASS;
export const INSET_PANEL_MUTED_CLASS = _INSET_PANEL_MUTED_CLASS;
export type BtnVariant = _BtnVariant;
export const BTN_VARIANT_CLASS = _BTN_VARIANT_CLASS;
export const ERROR_ACTION_CLASS = _ERROR_ACTION_CLASS;
export const GHOST_ACTION_CIRCLE_DENSE_CLASS = _GHOST_ACTION_CIRCLE_DENSE_CLASS;
export const GHOST_ACTION_CLASS = _GHOST_ACTION_CLASS;
export const GHOST_ACTION_DENSE_CLASS = _GHOST_ACTION_DENSE_CLASS;
export const GHOST_ACTION_ERROR_DENSE_CLASS = _GHOST_ACTION_ERROR_DENSE_CLASS;
export const GHOST_ACTION_PRINT_HIDDEN_CLASS = _GHOST_ACTION_PRINT_HIDDEN_CLASS;
export const GHOST_ACTION_SQUARE_CLASS = _GHOST_ACTION_SQUARE_CLASS;
export const LINK_ACTION_CLASS = _LINK_ACTION_CLASS;
export const LINK_ACTION_DENSE_CLASS = _LINK_ACTION_DENSE_CLASS;
export const OUTLINE_ACTION_DENSE_CLASS = _OUTLINE_ACTION_DENSE_CLASS;
export const OUTLINE_ACTION_ERROR_CLASS = _OUTLINE_ACTION_ERROR_CLASS;
export const OUTLINE_ACTION_ERROR_DENSE_CLASS = _OUTLINE_ACTION_ERROR_DENSE_CLASS;
export const OUTLINE_ACTION_JOIN_CLASS = _OUTLINE_ACTION_JOIN_CLASS;
export const OUTLINE_ACTION_PRINT_HIDDEN_CLASS = _OUTLINE_ACTION_PRINT_HIDDEN_CLASS;
export const OUTLINE_ACTION_SECONDARY_CLASS = _OUTLINE_ACTION_SECONDARY_CLASS;
export const SUCCESS_ACTION_CLASS = _SUCCESS_ACTION_CLASS;
