#!/usr/bin/env python3
"""
Video game studio data provider.
Outputs curated JSON array of gaming studios matching our job provider boards.
Each entry maps to the studios DB schema: id, name, website, location, size, type,
description, games, technologies, culture, interviewStyle, remoteWork.
"""
import json
import re
import sys


def slugify(name: str) -> str:
    """Convert studio name to URL-safe slug for id."""
    s = re.sub(r"[^a-z0-9]+", "-", name.lower().strip())
    return s.strip("-") or "studio"


# fmt: off
STUDIOS: list[dict] = [
    # ──────────────────────────────────────────────
    # AAA Studios
    # ──────────────────────────────────────────────
    {
        "name": "Riot Games",
        "website": "https://www.riotgames.com",
        "location": "Los Angeles, CA",
        "size": "5000+",
        "type": "AAA",
        "description": "Creator of League of Legends, VALORANT, Teamfight Tactics, and Legends of Runeterra. One of the world's largest game developers with studios globally.",
        "games": ["League of Legends", "VALORANT", "Teamfight Tactics", "Legends of Runeterra", "Wild Rift"],
        "technologies": ["C++", "Go", "Rust", "React", "Kubernetes", "AWS"],
        "interviewStyle": "Systems design, behavioral STAR, live coding, game design exercises",
        "remoteWork": False,
    },
    {
        "name": "Epic Games",
        "website": "https://www.epicgames.com",
        "location": "Cary, NC",
        "size": "3000+",
        "type": "AAA",
        "description": "Creator of Fortnite and Unreal Engine. Operates the Epic Games Store and develops foundational game engine technology.",
        "games": ["Fortnite", "Rocket League", "Fall Guys", "Unreal Tournament"],
        "technologies": ["Unreal Engine", "C++", "Blueprints", "Python", "AWS"],
        "interviewStyle": "Engine architecture, C++ deep-dives, systems design",
        "remoteWork": False,
    },
    {
        "name": "Blizzard Entertainment",
        "website": "https://www.blizzard.com",
        "location": "Irvine, CA",
        "size": "5000+",
        "type": "AAA",
        "description": "Legendary studio behind World of Warcraft, Overwatch, Diablo, StarCraft, and Hearthstone. Part of Activision Blizzard King.",
        "games": ["World of Warcraft", "Overwatch 2", "Diablo IV", "Hearthstone", "StarCraft II"],
        "technologies": ["C++", "C#", "Unity", "Proprietary engines", "Lua"],
        "interviewStyle": "Technical deep-dives, gameplay systems design, culture fit",
        "remoteWork": False,
    },
    {
        "name": "Rockstar Games",
        "website": "https://www.rockstargames.com",
        "location": "New York, NY",
        "size": "2000+",
        "type": "AAA",
        "description": "Developer of Grand Theft Auto, Red Dead Redemption, and Max Payne. Known for massive open-world games with cinematic narratives.",
        "games": ["Grand Theft Auto V", "Red Dead Redemption 2", "GTA Online", "Max Payne 3"],
        "technologies": ["RAGE Engine", "C++", "Proprietary tools", "Python"],
        "interviewStyle": "Technical interviews, portfolio review, multi-round process",
        "remoteWork": False,
    },
    {
        "name": "Electronic Arts",
        "website": "https://www.ea.com",
        "location": "Redwood City, CA",
        "size": "10000+",
        "type": "AAA",
        "description": "One of the world's largest publishers. Develops FIFA/EA Sports FC, Madden, Apex Legends, The Sims, and Battlefield franchises.",
        "games": ["EA Sports FC", "Apex Legends", "Battlefield", "The Sims 4", "Madden NFL", "Star Wars Jedi"],
        "technologies": ["Frostbite Engine", "C++", "Python", "Java", "AWS", "Source Engine"],
        "interviewStyle": "Behavioral, technical, systems design, team collaboration exercises",
        "remoteWork": True,
    },
    {
        "name": "Ubisoft",
        "website": "https://www.ubisoft.com",
        "location": "Paris, France",
        "size": "20000+",
        "type": "AAA",
        "description": "Global publisher behind Assassin's Creed, Far Cry, Rainbow Six, and Watch Dogs. Operates studios across 30+ countries.",
        "games": ["Assassin's Creed", "Far Cry", "Rainbow Six Siege", "Watch Dogs", "The Division"],
        "technologies": ["Anvil Engine", "Snowdrop Engine", "C++", "Python", "Ubisoft Connect"],
        "interviewStyle": "Multi-studio process, technical + creative assessments",
        "remoteWork": True,
    },
    {
        "name": "Activision",
        "website": "https://www.activision.com",
        "location": "Santa Monica, CA",
        "size": "10000+",
        "type": "AAA",
        "description": "Publisher of Call of Duty, one of the best-selling gaming franchises. Part of Activision Blizzard King (Microsoft).",
        "games": ["Call of Duty: Modern Warfare", "Call of Duty: Warzone", "Crash Bandicoot", "Tony Hawk's Pro Skater"],
        "technologies": ["IW Engine", "C++", "Proprietary tools", "Python"],
        "interviewStyle": "Technical deep-dives, engine programming, multiplayer systems",
        "remoteWork": False,
    },
    {
        "name": "Naughty Dog",
        "website": "https://www.naughtydog.com",
        "location": "Santa Monica, CA",
        "size": "500+",
        "type": "AAA",
        "description": "PlayStation first-party studio known for The Last of Us, Uncharted, and Jak and Daxter. Renowned for cinematic storytelling and technical excellence.",
        "games": ["The Last of Us Part II", "Uncharted 4", "The Last of Us Part I", "Jak and Daxter"],
        "technologies": ["Proprietary engine", "C++", "ICE Team tools", "PlayStation SDK"],
        "interviewStyle": "Portfolio-heavy, C++ systems, graphics programming, narrative design",
        "remoteWork": False,
    },
    {
        "name": "Insomniac Games",
        "website": "https://insomniac.games",
        "location": "Burbank, CA",
        "size": "500+",
        "type": "AAA",
        "description": "PlayStation first-party studio. Creator of Marvel's Spider-Man, Ratchet & Clank, and Resistance. Known for rapid iteration and polish.",
        "games": ["Marvel's Spider-Man 2", "Ratchet & Clank: Rift Apart", "Spider-Man: Miles Morales"],
        "technologies": ["Insomniac Engine", "C++", "PlayStation SDK", "Python"],
        "interviewStyle": "Technical + art portfolio review, gameplay programming tests",
        "remoteWork": False,
    },
    {
        "name": "Guerrilla Games",
        "website": "https://www.guerrilla-games.com",
        "location": "Amsterdam, Netherlands",
        "size": "400+",
        "type": "AAA",
        "description": "PlayStation first-party studio behind Horizon Zero Dawn and Horizon Forbidden West. Creators of the Decima Engine used by multiple studios.",
        "games": ["Horizon Forbidden West", "Horizon Zero Dawn", "Killzone Shadow Fall"],
        "technologies": ["Decima Engine", "C++", "Vulkan", "PlayStation SDK"],
        "interviewStyle": "Engine programming, open-world systems, graphics deep-dives",
        "remoteWork": False,
    },
    {
        "name": "Respawn Entertainment",
        "website": "https://www.respawn.com",
        "location": "Los Angeles, CA",
        "size": "500+",
        "type": "AAA",
        "description": "Creators of Apex Legends, Titanfall, and Star Wars Jedi. Founded by original Call of Duty creators. Part of EA.",
        "games": ["Apex Legends", "Star Wars Jedi: Survivor", "Titanfall 2"],
        "technologies": ["Source Engine", "Unreal Engine", "C++", "Python"],
        "interviewStyle": "FPS systems design, multiplayer networking, live service architecture",
        "remoteWork": True,
    },
    {
        "name": "Bungie",
        "website": "https://www.bungie.net",
        "location": "Bellevue, WA",
        "size": "1000+",
        "type": "AAA",
        "description": "Creators of Halo and Destiny. Pioneers of the live-service shooter model. Now part of Sony Interactive Entertainment.",
        "games": ["Destiny 2", "Marathon", "Halo"],
        "technologies": ["Tiger Engine", "C++", "C#", "Python", "AWS"],
        "interviewStyle": "Systems design, live service architecture, multiplayer networking",
        "remoteWork": True,
    },
    {
        "name": "Obsidian Entertainment",
        "website": "https://www.obsidian.net",
        "location": "Irvine, CA",
        "size": "200+",
        "type": "AAA",
        "description": "RPG specialists behind The Outer Worlds, Pillars of Eternity, Grounded, and Avowed. Part of Xbox Game Studios.",
        "games": ["Avowed", "The Outer Worlds", "Grounded", "Pillars of Eternity II"],
        "technologies": ["Unreal Engine", "Unity", "C++", "C#"],
        "interviewStyle": "RPG systems design, narrative design, world-building exercises",
        "remoteWork": True,
    },
    {
        "name": "Square Enix",
        "website": "https://www.square-enix.com",
        "location": "Tokyo, Japan",
        "size": "5000+",
        "type": "AAA",
        "description": "Japanese publisher behind Final Fantasy, Dragon Quest, Kingdom Hearts, and NieR. Multiple studios worldwide.",
        "games": ["Final Fantasy XVI", "Final Fantasy VII Remake", "Kingdom Hearts", "Dragon Quest"],
        "technologies": ["Luminous Engine", "Unreal Engine", "C++", "Crystal Tools"],
        "interviewStyle": "Technical assessments, JRPG systems knowledge, cross-cultural communication",
        "remoteWork": False,
    },
    {
        "name": "Sucker Punch Productions",
        "website": "https://www.suckerpunch.com",
        "location": "Bellevue, WA",
        "size": "200+",
        "type": "AAA",
        "description": "PlayStation first-party studio known for Ghost of Tsushima and InFamous. Renowned for open-world design and visual fidelity.",
        "games": ["Ghost of Tsushima", "InFamous Second Son", "Sly Cooper"],
        "technologies": ["Proprietary engine", "C++", "PlayStation SDK"],
        "interviewStyle": "Open-world systems, combat design, C++ architecture",
        "remoteWork": False,
    },
    {
        "name": "Arkane Studios",
        "website": "https://www.arkane-studios.com",
        "location": "Lyon, France",
        "size": "200+",
        "type": "AAA",
        "description": "Immersive sim masters behind Dishonored, Deathloop, and Prey. Known for emergent gameplay and player freedom. Part of Xbox.",
        "games": ["Deathloop", "Dishonored 2", "Prey", "Redfall"],
        "technologies": ["Void Engine", "id Tech", "CryEngine", "C++"],
        "interviewStyle": "Immersive sim design philosophy, level design tests, AI systems",
        "remoteWork": False,
    },
    {
        "name": "MachineGames",
        "website": "https://www.machinegames.com",
        "location": "Uppsala, Sweden",
        "size": "100+",
        "type": "AAA",
        "description": "Developer of the modern Wolfenstein series and Indiana Jones and the Great Circle. Part of Xbox/Bethesda.",
        "games": ["Indiana Jones and the Great Circle", "Wolfenstein II", "Wolfenstein: The New Order"],
        "technologies": ["id Tech Engine", "C++"],
        "interviewStyle": "FPS design, id Tech engine knowledge, narrative action design",
        "remoteWork": False,
    },
    {
        "name": "Treyarch",
        "website": "https://www.treyarch.com",
        "location": "Santa Monica, CA",
        "size": "500+",
        "type": "AAA",
        "description": "Call of Duty developer responsible for the Black Ops sub-series and Zombies mode. Part of Activision.",
        "games": ["Call of Duty: Black Ops Cold War", "Call of Duty: Black Ops 4", "Call of Duty: Black Ops III"],
        "technologies": ["IW Engine", "C++", "Proprietary tools"],
        "interviewStyle": "Multiplayer systems, engine programming, live ops",
        "remoteWork": False,
    },
    {
        "name": "Sledgehammer Games",
        "website": "https://www.sledgehammergames.com",
        "location": "San Mateo, CA",
        "size": "300+",
        "type": "AAA",
        "description": "Call of Duty developer behind Advanced Warfare, WWII, and Modern Warfare III. Part of Activision.",
        "games": ["Call of Duty: Modern Warfare III", "Call of Duty: WWII", "Call of Duty: Advanced Warfare"],
        "technologies": ["IW Engine", "C++", "Proprietary tools"],
        "interviewStyle": "FPS systems, engine programming, production pipeline",
        "remoteWork": False,
    },
    {
        "name": "Infinity Ward",
        "website": "https://www.infinityward.com",
        "location": "Woodland Hills, CA",
        "size": "500+",
        "type": "AAA",
        "description": "Original creators of Call of Duty. Developed Modern Warfare and Warzone. Part of Activision.",
        "games": ["Call of Duty: Modern Warfare II", "Call of Duty: Warzone 2.0", "Call of Duty 4: Modern Warfare"],
        "technologies": ["IW Engine", "C++", "Proprietary tools"],
        "interviewStyle": "Engine architecture, multiplayer networking, graphics programming",
        "remoteWork": False,
    },
    {
        "name": "2K Games",
        "website": "https://www.2k.com",
        "location": "Novato, CA",
        "size": "2000+",
        "type": "AAA",
        "description": "Publisher of NBA 2K, Civilization, BioShock, Borderlands, and WWE 2K. Part of Take-Two Interactive.",
        "games": ["NBA 2K", "Civilization VI", "BioShock", "Borderlands 3", "WWE 2K"],
        "technologies": ["Unreal Engine", "C++", "Proprietary engines"],
        "interviewStyle": "Sports sim systems, AI programming, production management",
        "remoteWork": True,
    },
    {
        "name": "Gearbox Software",
        "website": "https://www.gearboxsoftware.com",
        "location": "Frisco, TX",
        "size": "500+",
        "type": "AAA",
        "description": "Creators of Borderlands and developers of Half-Life expansions. Known for looter-shooters and co-op gameplay.",
        "games": ["Borderlands 3", "Tiny Tina's Wonderlands", "Borderlands 2", "Brothers in Arms"],
        "technologies": ["Unreal Engine", "C++", "Python"],
        "interviewStyle": "Unreal Engine expertise, gameplay systems, co-op multiplayer design",
        "remoteWork": True,
    },
    {
        "name": "Playground Games",
        "website": "https://playground-games.com",
        "location": "Leamington Spa, UK",
        "size": "300+",
        "type": "AAA",
        "description": "Xbox first-party studio behind Forza Horizon and the upcoming Fable reboot. Masters of open-world racing.",
        "games": ["Forza Horizon 5", "Fable", "Forza Horizon 4"],
        "technologies": ["ForzaTech Engine", "C++", "DirectX 12"],
        "interviewStyle": "Engine programming, open-world tech, graphics/rendering",
        "remoteWork": False,
    },
    {
        "name": "Larian Studios",
        "website": "https://larian.com",
        "location": "Ghent, Belgium",
        "size": "500+",
        "type": "AAA",
        "description": "Creators of Baldur's Gate 3 and the Divinity: Original Sin series. Known for deep RPG systems and player agency.",
        "games": ["Baldur's Gate 3", "Divinity: Original Sin 2", "Divinity: Original Sin"],
        "technologies": ["Divinity Engine", "C++", "Proprietary tools"],
        "interviewStyle": "RPG systems design, turn-based combat, narrative branching",
        "remoteWork": True,
    },
    {
        "name": "CD Projekt Red",
        "website": "https://www.cdprojektred.com",
        "location": "Warsaw, Poland",
        "size": "1000+",
        "type": "AAA",
        "description": "Creators of The Witcher series and Cyberpunk 2077. Also operates GOG.com digital storefront. Working on The Witcher 4.",
        "games": ["Cyberpunk 2077", "The Witcher 3: Wild Hunt", "Cyberpunk 2077: Phantom Liberty"],
        "technologies": ["REDengine", "Unreal Engine 5", "C++", "Lua"],
        "interviewStyle": "Open-world systems, quest design, technical architecture",
        "remoteWork": True,
    },
    {
        "name": "Avalanche Studios",
        "website": "https://avalanchestudios.com",
        "location": "Stockholm, Sweden",
        "size": "300+",
        "type": "AAA",
        "description": "Creators of Just Cause, Mad Max, and theHunter. Known for large-scale open-world destruction systems.",
        "games": ["Just Cause 4", "Mad Max", "theHunter: Call of the Wild", "Generation Zero"],
        "technologies": ["Apex Engine", "C++", "Proprietary tools"],
        "interviewStyle": "Open-world tech, destruction physics, engine programming",
        "remoteWork": False,
    },
    {
        "name": "Firaxis Games",
        "website": "https://firaxis.com",
        "location": "Sparks, MD",
        "size": "200+",
        "type": "AAA",
        "description": "Masters of strategy gaming. Creators of Civilization and XCOM. Part of 2K/Take-Two.",
        "games": ["Civilization VI", "XCOM 2", "Marvel's Midnight Suns"],
        "technologies": ["Proprietary engine", "C++", "Python", "Lua"],
        "interviewStyle": "Strategy game AI, turn-based systems, procedural generation",
        "remoteWork": True,
    },
    {
        "name": "Wargaming",
        "website": "https://wargaming.com",
        "location": "Nicosia, Cyprus",
        "size": "5000+",
        "type": "AAA",
        "description": "Developer and publisher of World of Tanks, World of Warships, and World of Warplanes. Global free-to-play MMO specialist.",
        "games": ["World of Tanks", "World of Warships", "World of Warplanes"],
        "technologies": ["BigWorld Engine", "C++", "Python", "Kubernetes"],
        "interviewStyle": "MMO architecture, free-to-play systems, server infrastructure",
        "remoteWork": True,
    },
    {
        "name": "Mojang Studios",
        "website": "https://www.minecraft.net",
        "location": "Stockholm, Sweden",
        "size": "600+",
        "type": "AAA",
        "description": "Creators of Minecraft, one of the best-selling games of all time. Part of Xbox Game Studios.",
        "games": ["Minecraft", "Minecraft Dungeons", "Minecraft Legends"],
        "technologies": ["Java", "C++", "Bedrock Engine", "Azure"],
        "interviewStyle": "Java/C++ systems, procedural generation, multiplayer architecture",
        "remoteWork": True,
    },
    {
        "name": "Amplitude Studios",
        "website": "https://www.amplitude-studios.com",
        "location": "Paris, France",
        "size": "100+",
        "type": "AAA",
        "description": "Strategy game studio behind Humankind and the Endless series. Part of Sega.",
        "games": ["Humankind", "Endless Space 2", "Endless Legend", "Dungeon of the Endless"],
        "technologies": ["Unity", "C#", "Proprietary tools"],
        "interviewStyle": "4X strategy design, AI systems, procedural content",
        "remoteWork": False,
    },
    {
        "name": "Cloud Imperium Games",
        "website": "https://cloudimperiumgames.com",
        "location": "Los Angeles, CA",
        "size": "1000+",
        "type": "AAA",
        "description": "Developer of Star Citizen, the most ambitious crowdfunded game. Building an unprecedented online space simulation.",
        "games": ["Star Citizen", "Squadron 42"],
        "technologies": ["CryEngine", "StarEngine", "C++", "AWS"],
        "interviewStyle": "Engine programming, networking, large-scale simulation systems",
        "remoteWork": True,
    },
    {
        "name": "Second Dinner",
        "website": "https://seconddinner.com",
        "location": "Irvine, CA",
        "size": "100+",
        "type": "AAA",
        "description": "Founded by former Hearthstone director Ben Brode. Creators of Marvel Snap.",
        "games": ["Marvel Snap"],
        "technologies": ["Unity", "C#", "Cloud infrastructure"],
        "interviewStyle": "Card game design, mobile-first development, live service",
        "remoteWork": True,
    },
    {
        "name": "Cloud Chamber",
        "website": "https://www.cloudchamberstudios.com",
        "location": "Novato, CA",
        "size": "200+",
        "type": "AAA",
        "description": "Developing the next BioShock game. 2K studio with teams in Novato and Montreal.",
        "games": ["BioShock (upcoming)"],
        "technologies": ["Unreal Engine 5", "C++"],
        "interviewStyle": "Immersive sim design, narrative systems, UE5 architecture",
        "remoteWork": False,
    },
    {
        "name": "Striking Distance Studios",
        "website": "https://strikingdistancestudios.com",
        "location": "San Ramon, CA",
        "size": "200+",
        "type": "AAA",
        "description": "Founded by former Dead Space creator Glen Schofield. Developers of The Callisto Protocol.",
        "games": ["The Callisto Protocol"],
        "technologies": ["Unreal Engine", "C++"],
        "interviewStyle": "Horror game design, UE systems, cinematic action",
        "remoteWork": False,
    },
    {
        "name": "Archetype Entertainment",
        "website": "https://www.archetypeentertainment.com",
        "location": "Austin, TX",
        "size": "100+",
        "type": "AAA",
        "description": "New RPG studio founded by former BioWare veterans including James Ohlen. Part of Wizards of the Coast.",
        "games": [],
        "technologies": ["Unreal Engine 5", "C++"],
        "interviewStyle": "RPG design, narrative systems, BioWare-style development",
        "remoteWork": True,
    },

    # ──────────────────────────────────────────────
    # Platform / Engine Companies
    # ──────────────────────────────────────────────
    {
        "name": "Unity Technologies",
        "website": "https://unity.com",
        "location": "San Francisco, CA",
        "size": "5000+",
        "type": "Platform",
        "description": "Creator of the Unity game engine, used by millions of developers. Powers mobile, console, VR, and web games worldwide.",
        "games": [],
        "technologies": ["Unity", "C#", "C++", "DOTS", "HDRP", "URP"],
        "interviewStyle": "Engine internals, rendering pipeline, C# architecture, tooling",
        "remoteWork": True,
    },
    {
        "name": "NVIDIA",
        "website": "https://www.nvidia.com",
        "location": "Santa Clara, CA",
        "size": "25000+",
        "type": "Platform",
        "description": "GPU manufacturer powering gaming, AI, and graphics. Develops GeForce GPUs, DLSS, RTX ray tracing, and game-critical drivers.",
        "games": [],
        "technologies": ["CUDA", "C++", "Vulkan", "DirectX", "OptiX", "TensorRT"],
        "interviewStyle": "GPU architecture, graphics programming, driver development, CUDA",
        "remoteWork": True,
    },
    {
        "name": "Valve",
        "website": "https://www.valvesoftware.com",
        "location": "Bellevue, WA",
        "size": "300+",
        "type": "Platform",
        "description": "Creator of Steam, Half-Life, Portal, Dota 2, and Counter-Strike. Operates the dominant PC gaming marketplace and makes the Steam Deck.",
        "games": ["Counter-Strike 2", "Dota 2", "Half-Life: Alyx", "Portal 2"],
        "technologies": ["Source 2 Engine", "C++", "Vulkan", "SteamOS", "Linux"],
        "interviewStyle": "Flat org, project-based hiring, deep technical interviews, self-direction",
        "remoteWork": False,
    },
    {
        "name": "Roblox",
        "website": "https://www.roblox.com",
        "location": "San Mateo, CA",
        "size": "2000+",
        "type": "Platform",
        "description": "Global platform for user-generated games with 65M+ daily active users. Combines game engine, social network, and marketplace.",
        "games": ["Roblox Platform"],
        "technologies": ["Luau", "C++", "Rust", "React", "Infrastructure at scale"],
        "interviewStyle": "Distributed systems, platform scale, Lua/Luau, safety systems",
        "remoteWork": True,
    },
    {
        "name": "Discord",
        "website": "https://discord.com",
        "location": "San Francisco, CA",
        "size": "600+",
        "type": "Platform",
        "description": "The leading voice, video, and text communication platform for gamers and communities. 200M+ monthly active users.",
        "games": [],
        "technologies": ["React", "React Native", "Rust", "Python", "Elixir", "C++"],
        "interviewStyle": "Systems design, real-time communication, scale, React architecture",
        "remoteWork": True,
    },

    # ──────────────────────────────────────────────
    # Mobile / Casual Studios
    # ──────────────────────────────────────────────
    {
        "name": "Supercell",
        "website": "https://supercell.com",
        "location": "Helsinki, Finland",
        "size": "400+",
        "type": "Mobile",
        "description": "Creators of Clash of Clans, Clash Royale, Brawl Stars, and Hay Day. Known for small-team culture and billion-dollar mobile hits.",
        "games": ["Clash of Clans", "Clash Royale", "Brawl Stars", "Hay Day", "Boom Beach"],
        "technologies": ["C++", "Proprietary engine", "AWS", "Kotlin", "Swift"],
        "interviewStyle": "Small-team mindset, game design portfolio, mobile F2P expertise",
        "remoteWork": False,
    },
    {
        "name": "Niantic",
        "website": "https://nianticlabs.com",
        "location": "San Francisco, CA",
        "size": "800+",
        "type": "Mobile",
        "description": "Pioneers of AR gaming with Pokemon GO, Ingress, and Peridot. Building the real-world metaverse with location-based experiences.",
        "games": ["Pokemon GO", "Ingress", "Peridot", "Monster Hunter Now"],
        "technologies": ["Unity", "AR Kit", "AR Core", "Java", "Kotlin", "Python", "Google Cloud"],
        "interviewStyle": "AR/VR systems, geolocation, mobile performance, ML/CV",
        "remoteWork": True,
    },
    {
        "name": "The Pokemon Company",
        "website": "https://www.pokemon.com",
        "location": "Tokyo, Japan",
        "size": "1000+",
        "type": "Mobile",
        "description": "Manages the Pokemon franchise including games, trading cards, anime, and merchandise. The highest-grossing media franchise ever.",
        "games": ["Pokemon Scarlet/Violet", "Pokemon GO", "Pokemon Unite", "Pokemon TCG"],
        "technologies": ["Unity", "C++", "GameFreak tools", "Mobile SDKs"],
        "interviewStyle": "Brand-conscious design, cross-platform development, Japanese business culture",
        "remoteWork": False,
    },
    {
        "name": "Voodoo",
        "website": "https://www.voodoo.io",
        "location": "Paris, France",
        "size": "500+",
        "type": "Mobile",
        "description": "Leading hyper-casual mobile game publisher with 6B+ downloads. Known for rapid prototyping and data-driven game design.",
        "games": ["Helix Jump", "Crowd City", "Hole.io", "Paper.io"],
        "technologies": ["Unity", "C#", "Data analytics", "A/B testing pipelines"],
        "interviewStyle": "Rapid prototyping, mobile UA metrics, data-driven design",
        "remoteWork": True,
    },
    {
        "name": "Jam City",
        "website": "https://www.jamcity.com",
        "location": "Los Angeles, CA",
        "size": "800+",
        "type": "Mobile",
        "description": "Mobile game studio behind Cookie Jam, Panda Pop, and Harry Potter: Hogwarts Mystery.",
        "games": ["Cookie Jam", "Panda Pop", "Harry Potter: Hogwarts Mystery", "Family Guy"],
        "technologies": ["Unity", "C#", "Cocos2d", "AWS"],
        "interviewStyle": "Mobile game design, LiveOps, monetization strategy",
        "remoteWork": True,
    },
    {
        "name": "Wildlife Studios",
        "website": "https://wildlifestudios.com",
        "location": "Sao Paulo, Brazil",
        "size": "1000+",
        "type": "Mobile",
        "description": "One of the largest mobile game developers globally. Known for Zooba, Tennis Clash, and Sniper 3D.",
        "games": ["Zooba", "Tennis Clash", "Sniper 3D", "War Machines"],
        "technologies": ["Unity", "C#", "Kotlin", "Python", "AWS"],
        "interviewStyle": "Mobile gaming systems, data science, live operations",
        "remoteWork": True,
    },
    {
        "name": "PlayQ",
        "website": "https://www.playq.com",
        "location": "San Diego, CA",
        "size": "100+",
        "type": "Mobile",
        "description": "Mobile-first studio specializing in narrative RPGs and puzzle games. Known for strong company culture.",
        "games": ["Storyngton Hall", "Animals & Coins"],
        "technologies": ["Unity", "C#", "Ruby", "AWS"],
        "interviewStyle": "Mobile architecture, narrative game design, culture fit",
        "remoteWork": True,
    },
    {
        "name": "Demiurge Studios",
        "website": "https://www.demiurgestudios.com",
        "location": "Cambridge, MA",
        "size": "50+",
        "type": "Mobile",
        "description": "Mobile and co-development studio behind Marvel Puzzle Quest. Also supports major AAA projects.",
        "games": ["Marvel Puzzle Quest", "Solitaire Blitz"],
        "technologies": ["Unity", "C#", "C++"],
        "interviewStyle": "Mobile game systems, co-dev collaboration, puzzle game design",
        "remoteWork": True,
    },

    # ──────────────────────────────────────────────
    # Indie / AA Studios
    # ──────────────────────────────────────────────
    {
        "name": "Double Fine Productions",
        "website": "https://www.doublefine.com",
        "location": "San Francisco, CA",
        "size": "70+",
        "type": "Indie",
        "description": "Tim Schafer's studio behind Psychonauts, Brutal Legend, and Broken Age. Part of Xbox Game Studios. Known for creative, humorous games.",
        "games": ["Psychonauts 2", "Broken Age", "Brutal Legend", "Day of the Tentacle Remastered"],
        "technologies": ["Unreal Engine", "Proprietary engine", "C++", "Lua"],
        "interviewStyle": "Creative game design, narrative writing, small-team collaboration",
        "remoteWork": True,
    },
    {
        "name": "Devolver Digital",
        "website": "https://www.devolverdigital.com",
        "location": "Austin, TX",
        "size": "50+",
        "type": "Indie",
        "description": "Indie publisher known for bold, unconventional games. Published Hades, Hotline Miami, Enter the Gungeon, Cult of the Lamb, and more.",
        "games": ["Cult of the Lamb", "Hades", "Hotline Miami", "Enter the Gungeon", "Inscryption"],
        "technologies": ["Various (publisher)", "Unity", "GameMaker", "Godot"],
        "interviewStyle": "Indie sensibility, marketing creativity, developer relations",
        "remoteWork": True,
    },
    {
        "name": "Coffee Stain Studios",
        "website": "https://www.coffeestainstudios.com",
        "location": "Skovde, Sweden",
        "size": "100+",
        "type": "Indie",
        "description": "Developer of Satisfactory, Deep Rock Galactic (publishing), and Goat Simulator. Also publishes third-party indie titles.",
        "games": ["Satisfactory", "Goat Simulator", "Deep Rock Galactic", "Valheim"],
        "technologies": ["Unreal Engine", "Unity", "C++", "C#"],
        "interviewStyle": "Indie game development, community management, UE/Unity",
        "remoteWork": True,
    },
    {
        "name": "Embark Studios",
        "website": "https://www.embark-studios.com",
        "location": "Stockholm, Sweden",
        "size": "300+",
        "type": "Indie",
        "description": "Founded by former EA DICE GM Patrick Soderlund. Building games with Rust and open-source technology. Created THE FINALS.",
        "games": ["THE FINALS", "ARC Raiders"],
        "technologies": ["Rust", "Vulkan", "Proprietary engine", "Open-source tools"],
        "interviewStyle": "Rust programming, modern engine architecture, open-source mindset",
        "remoteWork": True,
    },
    {
        "name": "Nightdive Studios",
        "website": "https://www.nightdivestudios.com",
        "location": "Portland, OR",
        "size": "30+",
        "type": "Indie",
        "description": "Specialists in remastering classic games. Behind System Shock Remake, Quake remasters, and KEX Engine technology.",
        "games": ["System Shock Remake", "Quake Enhanced", "PowerSlave Exhumed", "Turok Remastered"],
        "technologies": ["KEX Engine", "id Tech", "C++", "Vulkan"],
        "interviewStyle": "Retro game knowledge, engine porting, graphics modernization",
        "remoteWork": True,
    },
    {
        "name": "Annapurna Interactive",
        "website": "https://annapurnainteractive.com",
        "location": "Los Angeles, CA",
        "size": "50+",
        "type": "Indie",
        "description": "Prestige indie publisher behind Outer Wilds, Stray, What Remains of Edith Finch, and Cocoon.",
        "games": ["Outer Wilds", "Stray", "Cocoon", "What Remains of Edith Finch", "Neon White"],
        "technologies": ["Various (publisher)", "Unity", "Unreal Engine"],
        "interviewStyle": "Indie publishing, creative vision, developer partnerships",
        "remoteWork": True,
    },
    {
        "name": "Innersloth",
        "website": "https://innersloth.com",
        "location": "Remote",
        "size": "10+",
        "type": "Indie",
        "description": "Tiny studio behind Among Us, one of the most viral multiplayer games ever. Fully remote team.",
        "games": ["Among Us"],
        "technologies": ["Unity", "C#"],
        "interviewStyle": "Small-team dynamics, social deduction game design",
        "remoteWork": True,
    },
    {
        "name": "New Blood Interactive",
        "website": "https://newblood.games",
        "location": "Remote",
        "size": "20+",
        "type": "Indie",
        "description": "Retro FPS publisher and developer. Behind ULTRAKILL, DUSK, and Amid Evil. Champions boomer shooter renaissance.",
        "games": ["ULTRAKILL", "DUSK", "Amid Evil", "Gloomwood"],
        "technologies": ["Unity", "C#", "Quake-era tech"],
        "interviewStyle": "Retro FPS design, fast-paced gameplay systems",
        "remoteWork": True,
    },
    {
        "name": "Hopoo Games",
        "website": "https://hopoogames.com",
        "location": "Remote",
        "size": "10+",
        "type": "Indie",
        "description": "Creators of Risk of Rain and Risk of Rain 2. Small team known for roguelike mastery.",
        "games": ["Risk of Rain 2", "Risk of Rain", "Deadbolt"],
        "technologies": ["Unity", "C#"],
        "interviewStyle": "Roguelike design, procedural generation, small-team culture",
        "remoteWork": True,
    },
    {
        "name": "Monomi Park",
        "website": "https://www.monomipark.com",
        "location": "San Mateo, CA",
        "size": "20+",
        "type": "Indie",
        "description": "Creators of Slime Rancher and Slime Rancher 2. Charming simulation and farming games.",
        "games": ["Slime Rancher 2", "Slime Rancher"],
        "technologies": ["Unity", "C#"],
        "interviewStyle": "Simulation game design, Unity development, small team",
        "remoteWork": True,
    },
    {
        "name": "Giant Squid Studios",
        "website": "https://www.giantsquidstudios.com",
        "location": "Los Angeles, CA",
        "size": "15+",
        "type": "Indie",
        "description": "Art-driven studio by Matt Nava (Journey art director). Created ABZU and The Pathless.",
        "games": ["ABZU", "The Pathless"],
        "technologies": ["Unreal Engine", "C++"],
        "interviewStyle": "Art direction, visual storytelling, UE development",
        "remoteWork": False,
    },
    {
        "name": "Blackbird Interactive",
        "website": "https://blackbirdinteractive.com",
        "location": "Vancouver, BC",
        "size": "200+",
        "type": "Indie",
        "description": "Strategy game studio behind Homeworld 3 and Hardspace: Shipbreaker. Founded by Homeworld co-creator.",
        "games": ["Homeworld 3", "Hardspace: Shipbreaker", "Crossfire: Legion"],
        "technologies": ["Unity", "C#", "Proprietary tools"],
        "interviewStyle": "RTS design, 3D space simulation, Unity architecture",
        "remoteWork": True,
    },
    {
        "name": "Ionlands",
        "website": "https://ionlands.com",
        "location": "Berlin, Germany",
        "size": "10+",
        "type": "Indie",
        "description": "Tiny indie studio behind Cloudpunk, a neon-noir delivery game set in a cyberpunk city.",
        "games": ["Cloudpunk", "Nivalis"],
        "technologies": ["Unity", "C#"],
        "interviewStyle": "Indie development, world-building, small-team processes",
        "remoteWork": True,
    },
    {
        "name": "Netflix Games",
        "website": "https://www.netflix.com/games",
        "location": "Los Angeles, CA",
        "size": "500+",
        "type": "AAA",
        "description": "Netflix's gaming division. Acquired multiple studios and produces mobile and cloud games for Netflix subscribers.",
        "games": ["Oxenfree II", "Into the Breach", "Hades"],
        "technologies": ["Unity", "Unreal Engine", "C++", "C#"],
        "interviewStyle": "Mobile-first, subscription model design, cross-platform development",
        "remoteWork": True,
    },
]
# fmt: on


def get_studios() -> list[dict]:
    """Return studio data with generated IDs."""
    result = []
    for studio in STUDIOS:
        entry = {
            "id": slugify(studio["name"]),
            "name": studio["name"],
            "website": studio.get("website", ""),
            "location": studio.get("location", ""),
            "size": studio.get("size", ""),
            "type": studio.get("type", "Indie"),
            "description": studio.get("description", ""),
            "games": studio.get("games", []),
            "technologies": studio.get("technologies", []),
            "interviewStyle": studio.get("interviewStyle", ""),
            "remoteWork": studio.get("remoteWork", None),
        }
        result.append(entry)
    return result


if __name__ == "__main__":
    result = get_studios()
    print(json.dumps(result, indent=2))
