import type { chatHistory } from "../db/schema/chat-history";
import type { coverLetters } from "../db/schema/cover-letters";
import type { gamification } from "../db/schema/gamification";
import type { interviewSessions } from "../db/schema/interviews";
import type { portfolioProjects, portfolios } from "../db/schema/portfolios";
import type { resumes } from "../db/schema/resumes";
import type { skillMappings } from "../db/schema/skill-mappings";
type ResumeInsert = typeof resumes.$inferInsert;
type CoverLetterInsert = typeof coverLetters.$inferInsert;
type PortfolioInsert = typeof portfolios.$inferInsert;
type PortfolioProjectInsert = typeof portfolioProjects.$inferInsert;
type InterviewSessionInsert = typeof interviewSessions.$inferInsert;
type GamificationInsert = typeof gamification.$inferInsert;
type SkillMappingInsert = typeof skillMappings.$inferInsert;
type ChatHistoryInsert = typeof chatHistory.$inferInsert;
export declare const omitImportMetadata: (value: Record<string, unknown>) => Record<string, unknown>;
export declare const sanitizeImportedSettings: (value: unknown) => Record<string, unknown>;
export declare const parseResumeInsert: (value: unknown) => ResumeInsert | null;
export declare const parseCoverLetterInsert: (value: unknown) => CoverLetterInsert | null;
export declare const parsePortfolioInsert: (value: unknown) => PortfolioInsert | null;
export declare const parsePortfolioProjectInsert: (value: unknown) => PortfolioProjectInsert | null;
export declare const parseInterviewSessionInsert: (value: unknown) => InterviewSessionInsert | null;
export declare const parseGamificationInsert: (value: unknown) => GamificationInsert | null;
export declare const parseSkillMappingInsert: (value: unknown) => SkillMappingInsert | null;
export declare const parseChatHistoryInsert: (value: unknown) => ChatHistoryInsert | null;
export declare const resolveProfileId: () => string;
export declare const resolveSettingsId: () => string;
export {};
