import type { JsonObject } from "@bao/shared/utils/json";
import type { chatHistory } from "../db/schema/chat-history";
import type { coverLetters } from "../db/schema/cover-letters";
import type { gamification } from "../db/schema/gamification";
import type { interviewSessions } from "../db/schema/interviews";
import type { portfolioProjects, portfolios } from "../db/schema/portfolios";
import type { resumes } from "../db/schema/resumes";
import type { skillMappings } from "../db/schema/skill-mappings";
type ResumeInsert = typeof resumes.$inferInsert;
type CoverLetterInsert = typeof coverLetters.$inferInsert;
type PortfolioInsert = typeof portfolios.$inferInsert;
type PortfolioProjectInsert = typeof portfolioProjects.$inferInsert;
type InterviewSessionInsert = typeof interviewSessions.$inferInsert;
type GamificationInsert = typeof gamification.$inferInsert;
type SkillMappingInsert = typeof skillMappings.$inferInsert;
type ChatHistoryInsert = typeof chatHistory.$inferInsert;
export declare const omitImportMetadata: <T extends object>(value: T) => JsonObject;
export declare const sanitizeImportedSettings: <T>(value: T) => JsonObject;
export declare const parseResumeInsert: <T>(value: T) => ResumeInsert | null;
export declare const parseCoverLetterInsert: <T>(value: T) => CoverLetterInsert | null;
export declare const parsePortfolioInsert: <T>(value: T) => PortfolioInsert | null;
export declare const parsePortfolioProjectInsert: <T>(value: T) => PortfolioProjectInsert | null;
export declare const parseInterviewSessionInsert: <T>(value: T) => InterviewSessionInsert | null;
export declare const parseGamificationInsert: <T>(value: T) => GamificationInsert | null;
export declare const parseSkillMappingInsert: <T>(value: T) => SkillMappingInsert | null;
export declare const parseChatHistoryInsert: <T>(value: T) => ChatHistoryInsert | null;
export declare const resolveProfileId: () => string;
export {};
