import { type SkillCategory, type SkillEvidence, type SkillMapping } from "@bao/shared/types/skill-mapping";
import type { JsonArray } from "@bao/shared/utils/json";
import type { skillMappings } from "../db/schema/skill-mappings";
type SkillMappingRow = typeof skillMappings.$inferSelect;
type DemandLevel = SkillMapping["demandLevel"];
export declare const normalizeSkillCategory: (value: string | null) => SkillCategory;
export declare const normalizeDemandLevel: <T>(value: T) => DemandLevel;
export declare const normalizeEvidenceEntries: (value: JsonArray | null | undefined) => SkillEvidence[];
export declare const skillMappingFromRow: (row: SkillMappingRow) => SkillMapping;
export {};
