/**
 * Generates the resume preview theme stylesheet from the canonical
 * RESUME_EXPORT_THEME_CONFIGS (packages/shared/src/constants/export-resume-theme.ts).
 *
 * SSOT law: the TS constants are the single owner of export theme colors.
 * This generator emits the ONLY CSS surface allowed to carry those raw
 * values; scripts/validate-resume-preview-css.ts fails on any drift, so the
 * generated file cannot be hand-edited or forked.
 */

import { writeFile } from "node:fs/promises";
import { RESUME_EXPORT_THEME_CONFIGS } from "../packages/shared/src/constants/export-resume-theme";
import type { ResumeTemplate } from "../packages/shared/src/constants/resume";
import { RESUME_TEMPLATE_OPTIONS } from "../packages/shared/src/constants/resume";
import { resumePreviewThemeClass } from "../packages/shared/src/utils/export-contract";
import { writeOutput } from "./utils/cli-output";

export const RESUME_PREVIEW_CSS_PATH =
  "packages/client/assets/css/tokens-resume-preview.generated.css";

const GENERATED_HEADER =
  "/* GENERATED by scripts/generate-resume-preview-css.ts from RESUME_EXPORT_THEME_CONFIGS.\n" +
  " * Do not edit by hand — drift fails validate:resume-preview-css. */";

type ExportRgbColor = { r: number; g: number; b: number };

/** 0..1 float channels in RESUME_EXPORT_THEME_CONFIGS map to 8-bit CSS channels. */
const RGB_CHANNEL_MAX = 255;

const toCssRgb = (color: ExportRgbColor): string =>
  `rgb(${Math.round(color.r * RGB_CHANNEL_MAX)} ${Math.round(color.g * RGB_CHANNEL_MAX)} ${Math.round(color.b * RGB_CHANNEL_MAX)})`;

const renderThemeBlock = (template: ResumeTemplate): string => {
  const { colors } = RESUME_EXPORT_THEME_CONFIGS[template].pdf;
  const themeClass = `.${resumePreviewThemeClass(template)}`;
  return [
    `${themeClass} {`,
    `  --resume-preview-primary: ${toCssRgb(colors.primary)};`,
    `  --resume-preview-accent: ${toCssRgb(colors.accent)};`,
    `  --resume-preview-secondary: ${toCssRgb(colors.secondary)};`,
    `  background-color: ${toCssRgb(colors.background)};`,
    `  color: ${toCssRgb(colors.text)};`,
    `}`,
  ].join("\n");
};

const renderHeaderVariantBlock = (template: ResumeTemplate): string => {
  const { colors, layout } = RESUME_EXPORT_THEME_CONFIGS[template].pdf;
  const themeClass = `.${resumePreviewThemeClass(template)}`;
  if (layout.headerStyle === "banner") {
    return [
      `${themeClass} .resume-preview-header {`,
      `  background-color: var(--resume-preview-primary);`,
      `  color: ${toCssRgb(colors.text)};`,
      `  border-color: var(--resume-preview-accent);`,
      `}`,
    ].join("\n");
  }
  if (layout.dividerStyle === "accent-bar") {
    return [
      `${themeClass} .resume-preview-header {`,
      `  border-color: var(--resume-preview-accent);`,
      `  border-bottom-width: 6px;`,
      `}`,
    ].join("\n");
  }
  return [
    `${themeClass} .resume-preview-header {`,
    `  border-color: var(--resume-preview-secondary);`,
    `}`,
  ].join("\n");
};

const SHARED_CONSUMER_BLOCK = `.resume-preview-section-title {
  color: var(--resume-preview-primary);
}

.resume-preview-company {
  color: var(--resume-preview-accent);
}

.resume-preview-meta {
  color: var(--resume-preview-secondary);
}

.resume-preview-skill-badge {
  border-color: var(--resume-preview-primary);
  color: var(--resume-preview-primary);
}`;

export const renderResumePreviewCss = (): string =>
  [
    GENERATED_HEADER,
    ...RESUME_TEMPLATE_OPTIONS.map((template) => renderThemeBlock(template)),
    ...RESUME_TEMPLATE_OPTIONS.map((template) => renderHeaderVariantBlock(template)),
    SHARED_CONSUMER_BLOCK,
    "",
  ].join("\n\n");

if (import.meta.main) {
  await writeFile(RESUME_PREVIEW_CSS_PATH, renderResumePreviewCss(), "utf8");
  await writeOutput(`Wrote ${RESUME_PREVIEW_CSS_PATH}`);
}
