/**
 * Generates the resume preview theme stylesheet from the canonical
 * RESUME_EXPORT_THEME_CONFIGS (packages/shared/src/constants/export-layout.ts).
 *
 * SSOT law: the TS constants are the single owner of export theme colors.
 * This generator emits the ONLY CSS surface allowed to carry those raw
 * values; scripts/validate-resume-preview-css.ts fails on any drift, so the
 * generated file cannot be hand-edited or forked.
 */

import { writeFile } from "node:fs/promises";
import { RESUME_EXPORT_THEME_CONFIGS } from "../packages/shared/src/constants/export-layout";
import type { ResumeTemplate } from "../packages/shared/src/constants/resume";
import { RESUME_TEMPLATE_OPTIONS } from "../packages/shared/src/constants/resume";

export const RESUME_PREVIEW_CSS_PATH =
  "packages/client/assets/css/resume-preview.generated.css";

const GENERATED_HEADER =
  "/* GENERATED by scripts/generate-resume-preview-css.ts from RESUME_EXPORT_THEME_CONFIGS.\n" +
  " * Do not edit by hand — drift fails validate:resume-preview-css. */";

type ExportRgbColor = { r: number; g: number; b: number };

const toCssRgb = (color: ExportRgbColor): string =>
  `rgb(${Math.round(color.r * 255)} ${Math.round(color.g * 255)} ${Math.round(color.b * 255)})`;

export const resumePreviewThemeClass = (template: ResumeTemplate): string =>
  `resume-preview-theme-${template}`;

const renderThemeBlock = (template: ResumeTemplate): string => {
  const { pdf } = RESUME_EXPORT_THEME_CONFIGS[template];
  const { colors, layout } = pdf;
  const themeClass = `.${resumePreviewThemeClass(template)}`;
  const lines: string[] = [
    `${themeClass} {`,
    `  --resume-preview-primary: ${toCssRgb(colors.primary)};`,
    `  --resume-preview-accent: ${toCssRgb(colors.accent)};`,
    `  --resume-preview-secondary: ${toCssRgb(colors.secondary)};`,
    `  background-color: ${toCssRgb(colors.background)};`,
    `  color: ${toCssRgb(colors.text)};`,
    `}`,
  ];

  if (layout.headerStyle === "banner") {
    lines.push(
      `${themeClass} .resume-preview-header {`,
      `  background-color: var(--resume-preview-primary);`,
      `  color: ${toCssRgb(colors.text)};`,
      `  border-color: var(--resume-preview-accent);`,
      `}`,
    );
  } else if (layout.dividerStyle === "accent-bar") {
    lines.push(
      `${themeClass} .resume-preview-header {`,
      `  border-color: var(--resume-preview-accent);`,
      `  border-bottom-width: 6px;`,
      `}`,
    );
  } else {
    lines.push(
      `${themeClass} .resume-preview-header {`,
      `  border-color: var(--resume-preview-secondary);`,
      `}`,
    );
  }

  return lines.join("\n");
};

const SHARED_CONSUMER_BLOCK = `.resume-preview-section-title {
  color: var(--resume-preview-primary);
}

.resume-preview-company {
  color: var(--resume-preview-accent);
}

.resume-preview-meta {
  color: var(--resume-preview-secondary);
}

.resume-preview-skill-badge {
  border-color: var(--resume-preview-primary);
  color: var(--resume-preview-primary);
}`;

export const renderResumePreviewCss = (): string =>
  [
    GENERATED_HEADER,
    ...RESUME_TEMPLATE_OPTIONS.map((template) => renderThemeBlock(template)),
    SHARED_CONSUMER_BLOCK,
    "",
  ].join("\n\n");

if (import.meta.main) {
  await writeFile(RESUME_PREVIEW_CSS_PATH, renderResumePreviewCss(), "utf8");
  console.log(`Wrote ${RESUME_PREVIEW_CSS_PATH}`);
}
